<#
.SYNOPSIS
  Apply reviewed formula whitelist candidates as SVG overlays in a copied PPTX.

.DESCRIPTION
  Reads formula-review.csv, renders rows with SuggestedAction=ReviewWhitelistConversion
  to SVG through Render-FormulaSvg.mjs, inserts the SVG at the matched shape bounds,
  hides the original text shape, and saves a new PPTX. The source PPTX is never modified.

.PARAMETER InputPath
  Source .pptx/.pptm file.

.PARAMETER FormulaReviewCsv
  formula-review.csv generated by Invoke-PhysicsPptWorkflow.ps1.

.PARAMETER OutputPath
  New PPTX path to save.

.PARAMETER SvgOutputDir
  Directory for generated SVG files. Defaults next to OutputPath.

.PARAMETER ReportPath
  CSV report path. Defaults next to OutputPath.

.PARAMETER MaxItems
  Maximum whitelist rows to apply in one run. Defaults to 10.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$FormulaReviewCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$SvgOutputDir,

    [string]$ReportPath,

    [string]$NodeExe = 'node',

    [ValidateRange(1, 100)]
    [int]$MaxItems = 10
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:MsoTrue = -1
$script:MsoFalse = 0

function Convert-ToSafePathSegment {
    param([string]$Name)
    $safe = $Name
    foreach ($ch in [System.IO.Path]::GetInvalidFileNameChars()) {
        $safe = $safe.Replace([string]$ch, '_')
    }
    $safe = $safe -replace '\s+', '_'
    $safe = $safe -replace '[^\p{L}\p{Nd}_-]+', '_'
    $safe = $safe.Trim('_')
    if ([string]::IsNullOrWhiteSpace($safe)) { return 'formula' }
    return $safe
}

function Get-FormulaDetailValue {
    param([string]$Details, [string]$Key)
    if ([string]::IsNullOrWhiteSpace($Details)) { return '' }
    $pattern = '(?:^|;\s*)' + [regex]::Escape($Key) + '=(.*?)(?=;\s*\w+=|$)'
    $match = [regex]::Match($Details, $pattern)
    if (-not $match.Success) { return '' }
    return $match.Groups[1].Value.Trim()
}

function Get-ShapeText {
    param($Shape)
    try {
        if ($null -ne $Shape.TextFrame2 -and $Shape.TextFrame2.HasText -eq $script:MsoTrue) {
            return [string]$Shape.TextFrame2.TextRange.Text
        }
    } catch { }
    return ''
}

function Get-NormalizedFormulaText {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return '' }
    return (($Text -replace '\s+', '') -replace '＝', '=').Trim()
}

function Find-MatchingShape {
    param($Slide, [string]$ShapeName, [string]$FormulaText)
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    $fallback = $null

    foreach ($shape in $Slide.Shapes) {
        try {
            if ([string]$shape.Name -ne $ShapeName) { continue }
            if ($null -eq $fallback) { $fallback = $shape }
            $shapeText = Get-ShapeText -Shape $shape
            $shapeNorm = Get-NormalizedFormulaText -Text $shapeText
            if (-not [string]::IsNullOrWhiteSpace($formulaNorm) -and $shapeNorm.Contains($formulaNorm)) {
                return $shape
            }
        } catch { }
    }

    return $fallback
}

function Add-ReportRow {
    param(
        [System.Collections.Generic.List[object]]$Rows,
        [string]$File,
        [int]$Slide,
        [string]$Shape,
        [string]$Issue,
        [string]$Details
    )

    $Rows.Add([pscustomobject]@{
        Timestamp = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        File = $File
        Slide = $Slide
        Shape = $Shape
        Issue = $Issue
        Details = $Details
    }) | Out-Null
}

function Write-Report {
    param([System.Collections.Generic.List[object]]$Rows, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = $Rows | ConvertTo-Csv -NoTypeInformation
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

$InputPath = [System.IO.Path]::GetFullPath($InputPath)
$FormulaReviewCsv = [System.IO.Path]::GetFullPath($FormulaReviewCsv)
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if ([string]::IsNullOrWhiteSpace($SvgOutputDir)) {
    $SvgOutputDir = Join-Path (Split-Path -Parent $OutputPath) 'formula-svg'
}
$SvgOutputDir = [System.IO.Path]::GetFullPath($SvgOutputDir)
if ([string]::IsNullOrWhiteSpace($ReportPath)) {
    $ReportPath = Join-Path (Split-Path -Parent $OutputPath) 'formula-svg-apply-report.csv'
}
$ReportPath = [System.IO.Path]::GetFullPath($ReportPath)

if (-not (Test-Path -LiteralPath $InputPath)) { throw "InputPath not found: $InputPath" }
if (-not (Test-Path -LiteralPath $FormulaReviewCsv)) { throw "FormulaReviewCsv not found: $FormulaReviewCsv" }
if (-not (Test-Path -LiteralPath $SvgOutputDir)) { New-Item -ItemType Directory -Path $SvgOutputDir -Force | Out-Null }
$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
$reportDir = Split-Path -Parent $ReportPath
if (-not (Test-Path -LiteralPath $reportDir)) { New-Item -ItemType Directory -Path $reportDir -Force | Out-Null }

$renderer = Join-Path $PSScriptRoot 'Render-FormulaSvg.mjs'
if (-not (Test-Path -LiteralPath $renderer)) { throw "Renderer not found: $renderer" }

$rows = New-Object System.Collections.Generic.List[object]
$reviewRows = @(
    Import-Csv -LiteralPath $FormulaReviewCsv -Encoding UTF8 |
        Where-Object { $_.SuggestedAction -eq 'ReviewWhitelistConversion' } |
        Select-Object -First $MaxItems
)

if ($reviewRows.Count -eq 0) {
    Add-ReportRow -Rows $rows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide 0 -Shape '(presentation)' -Issue 'NoFormulaWhitelistCandidate' -Details 'No ReviewWhitelistConversion rows found.'
    Write-Report -Rows $rows -Path $ReportPath
    Write-Host "Report saved: $ReportPath"
    return
}

Copy-Item -LiteralPath $InputPath -Destination $OutputPath -Force

$pp = $null
$pres = $null
try {
    $pp = New-Object -ComObject PowerPoint.Application
    $pp.Visible = $script:MsoTrue
    $pres = $pp.Presentations.Open($OutputPath, $script:MsoFalse, $script:MsoFalse, $script:MsoFalse)

    foreach ($row in $reviewRows) {
        $slideNo = [int]$row.Slide
        $shapeName = [string]$row.Shape
        $tex = Get-FormulaDetailValue -Details ([string]$row.WhitelistCandidate) -Key 'targetTex'
        if ([string]::IsNullOrWhiteSpace($tex)) {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgSkipped' -Details 'WhitelistCandidate does not contain targetTex.'
            continue
        }

        $svgName = 'slide-{0:000}-{1}.svg' -f $slideNo, (Convert-ToSafePathSegment -Name $shapeName)
        $svgPath = Join-Path $SvgOutputDir $svgName
        $renderArgs = @($renderer, '--tex', $tex, '--out', $svgPath)
        $renderOutput = & $NodeExe @renderArgs 2>&1
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $svgPath)) {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgRenderFailed' -Details (($renderOutput | Out-String).Trim())
            continue
        }

        try {
            $slide = $pres.Slides.Item($slideNo)
            $shape = Find-MatchingShape -Slide $slide -ShapeName $shapeName -FormulaText ([string]$row.FormulaText)
            if ($null -eq $shape) {
                Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaShapeNotFound' -Details ([string]$row.FormulaText)
                continue
            }

            $left = [single]$shape.Left
            $top = [single]$shape.Top
            $width = [single]$shape.Width
            $height = [single]$shape.Height
            $inserted = $slide.Shapes.AddPicture($svgPath, $script:MsoFalse, $script:MsoTrue, $left, $top, $width, $height)
            $inserted.Name = 'FormulaSvg_' + (Convert-ToSafePathSegment -Name $shapeName)
            $shape.Visible = $script:MsoFalse
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgInserted' -Details ("tex={0}; svg={1}; original hidden." -f $tex, $svgPath)
        } catch {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgInsertFailed' -Details $_.Exception.Message
        }
    }

    $pres.SaveAs($OutputPath)
    Add-ReportRow -Rows $rows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide 0 -Shape '(presentation)' -Issue 'SavedAs' -Details $OutputPath
} finally {
    if ($null -ne $pres) {
        try { $pres.Close() | Out-Null } catch { }
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($pres) | Out-Null
    }
    if ($null -ne $pp) {
        try { $pp.Quit() | Out-Null } catch { }
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($pp) | Out-Null
    }
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
}

Write-Report -Rows $rows -Path $ReportPath
Write-Host "Report saved: $ReportPath"
Write-Host "Output saved: $OutputPath"
