<#
.SYNOPSIS
  Apply low-risk fixes from a visual audit report to a copied PPTX.

.DESCRIPTION
  Reads pptx-visual-audit.csv, copies the source PPTX, and fixes only
  deterministic layout issues that do not alter text content: currently this
  means shifting shapes back inside the slide bounds. Blank-slide removal and
  text rewriting are intentionally not performed.

.PARAMETER InputPath
  Source .pptx/.pptm file.

.PARAMETER VisualAuditCsv
  CSV generated by Export-PptxVisualAudit.ps1.

.PARAMETER OutputPath
  New PPTX path to save.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$VisualAuditCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [ValidateRange(0, 40)]
    [double]$MarginPt = 4.0,

    [switch]$IncludeWarnings
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:MsoTrue = -1
$script:MsoFalse = 0

function Add-FixRow {
    param(
        [System.Collections.Generic.List[object]]$Rows,
        [string]$File,
        [int]$Slide,
        [string]$Shape,
        [string]$Issue,
        [string]$Status,
        [string]$Details
    )
    $Rows.Add([pscustomobject]@{
        Timestamp = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        File = $File
        Slide = $Slide
        Shape = $Shape
        Issue = $Issue
        Status = $Status
        Details = $Details
    }) | Out-Null
}

function Write-Utf8BomCsv {
    param([object[]]$Rows, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = $Rows | ConvertTo-Csv -NoTypeInformation
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

$InputPath = [System.IO.Path]::GetFullPath($InputPath)
$VisualAuditCsv = [System.IO.Path]::GetFullPath($VisualAuditCsv)
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if (-not (Test-Path -LiteralPath $InputPath)) { throw "InputPath not found: $InputPath" }
if (-not (Test-Path -LiteralPath $VisualAuditCsv)) { throw "VisualAuditCsv not found: $VisualAuditCsv" }

$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

$rows = @(
    Import-Csv -LiteralPath $VisualAuditCsv -Encoding UTF8 |
        Where-Object {
            $_.Issue -eq 'ShapeOutOfSlideBounds' -and
            $_.Shape -ne '(slide)' -and
            ($_.Severity -eq 'Error' -or ($IncludeWarnings -and $_.Severity -eq 'Warning'))
        }
)

$reportRows = New-Object System.Collections.Generic.List[object]
Copy-Item -LiteralPath $InputPath -Destination $OutputPath -Force

$pp = $null
$pres = $null
try {
    $pp = New-Object -ComObject PowerPoint.Application
    $pp.Visible = $script:MsoTrue
    $pres = $pp.Presentations.Open($OutputPath, $script:MsoFalse, $script:MsoFalse, $script:MsoFalse)
    $slideWidth = [double]$pres.PageSetup.SlideWidth
    $slideHeight = [double]$pres.PageSetup.SlideHeight

    foreach ($row in $rows) {
        $slideNo = [int]$row.Slide
        $shapeName = [string]$row.Shape
        try {
            $slide = $pres.Slides.Item($slideNo)
            $shape = $null
            foreach ($candidate in $slide.Shapes) {
                if ([string]$candidate.Name -eq $shapeName) {
                    $shape = $candidate
                    break
                }
            }
            if ($null -eq $shape) {
                Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide $slideNo -Shape $shapeName -Issue 'ShapeOutOfSlideBounds' -Status 'ShapeNotFound' -Details ''
                continue
            }

            $oldLeft = [double]$shape.Left
            $oldTop = [double]$shape.Top
            $oldWidth = [double]$shape.Width
            $oldHeight = [double]$shape.Height
            $oldRight = $oldLeft + $oldWidth
            $oldBottom = $oldTop + $oldHeight

            if ($oldWidth -le 0 -or $oldHeight -le 0) {
                Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide $slideNo -Shape $shapeName -Issue 'ShapeOutOfSlideBounds' -Status 'SkippedInvalidSize' -Details "width=$oldWidth; height=$oldHeight"
                continue
            }

            $intersectsSlide = ($oldRight -gt 0 -and $oldBottom -gt 0 -and $oldLeft -lt $slideWidth -and $oldTop -lt $slideHeight)
            if (-not $intersectsSlide) {
                Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide $slideNo -Shape $shapeName -Issue 'ShapeOutOfSlideBounds' -Status 'SkippedOutsideCanvas' -Details ("left={0:N1}; top={1:N1}; right={2:N1}; bottom={3:N1}; slide={4:N1}x{5:N1}" -f $oldLeft, $oldTop, $oldRight, $oldBottom, $slideWidth, $slideHeight)
                continue
            }

            $targetWidth = $oldWidth
            $targetHeight = $oldHeight
            $maxWidth = [Math]::Max(1, $slideWidth - (2 * $MarginPt))
            $maxHeight = [Math]::Max(1, $slideHeight - (2 * $MarginPt))
            if ($targetWidth -gt $maxWidth -or $targetHeight -gt $maxHeight) {
                Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide $slideNo -Shape $shapeName -Issue 'ShapeOutOfSlideBounds' -Status 'SkippedRequiresResize' -Details ("size={0:N1}x{1:N1}; maxSafe={2:N1}x{3:N1}; left={4:N1}; top={5:N1}" -f $oldWidth, $oldHeight, $maxWidth, $maxHeight, $oldLeft, $oldTop)
                continue
            }

            $newLeft = $oldLeft
            $newTop = $oldTop
            if ($newLeft -lt $MarginPt) { $newLeft = $MarginPt }
            if ($newTop -lt $MarginPt) { $newTop = $MarginPt }
            if (($newLeft + $targetWidth) -gt ($slideWidth - $MarginPt)) { $newLeft = $slideWidth - $MarginPt - $targetWidth }
            if (($newTop + $targetHeight) -gt ($slideHeight - $MarginPt)) { $newTop = $slideHeight - $MarginPt - $targetHeight }
            if ($newLeft -lt $MarginPt) { $newLeft = $MarginPt }
            if ($newTop -lt $MarginPt) { $newTop = $MarginPt }

            $shape.Left = [single]$newLeft
            $shape.Top = [single]$newTop

            Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide $slideNo -Shape $shapeName -Issue 'ShapeOutOfSlideBounds' -Status 'MovedInsideSlide' -Details ("left {0:N1}->{1:N1}; top {2:N1}->{3:N1}; size {4:N1}x{5:N1}->{6:N1}x{7:N1}" -f $oldLeft, $newLeft, $oldTop, $newTop, $oldWidth, $oldHeight, $targetWidth, $targetHeight)
        } catch {
            Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide $slideNo -Shape $shapeName -Issue 'ShapeOutOfSlideBounds' -Status 'Failed' -Details $_.Exception.Message
        }
    }

    $pres.SaveAs($OutputPath)
    Add-FixRow -Rows $reportRows -File ([System.IO.Path]::GetFileName($InputPath)) -Slide 0 -Shape '(presentation)' -Issue 'SavedAs' -Status 'Saved' -Details $OutputPath
} finally {
    if ($null -ne $pres) {
        try { $pres.Close() | Out-Null } catch { }
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($pres) | Out-Null
    }
    if ($null -ne $pp) {
        try { $pp.Quit() | Out-Null } catch { }
        [System.Runtime.InteropServices.Marshal]::ReleaseComObject($pp) | Out-Null
    }
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
}

$reportPath = Join-Path $outDir 'pptx-visual-audit-fixes.csv'
Write-Utf8BomCsv -Rows $reportRows.ToArray() -Path $reportPath

Write-Host "Visual audit fixes done: $OutputPath"
Write-Host "Report saved: $reportPath"
