<#
.SYNOPSIS
  Apply reviewed formula whitelist candidates as OfficeMath/OMML in a copied PPTX.

.DESCRIPTION
  Reads formula-review.csv and formula-omml-candidates.csv, copies the source
  PPTX, replaces exact-match text formula paragraphs with a14:m/m:oMath
  fragments, and writes a report. The source PPTX is never modified.

.PARAMETER InputPath
  Source .pptx file.

.PARAMETER FormulaReviewCsv
  formula-review.csv generated by Invoke-PhysicsPptWorkflow.ps1.

.PARAMETER OmmlCandidateCsv
  formula-omml-candidates.csv generated by Export-FormulaOmmlCandidates.ps1.

.PARAMETER OutputPath
  New PPTX path to save.

.PARAMETER ReviewFileName
  Original PPTX file name used in formula-review.csv. Defaults to InputPath file name.

.PARAMETER ReportPath
  CSV report path. Defaults next to OutputPath.

.PARAMETER MaxItems
  Maximum whitelist rows to apply in one run. Defaults to 10.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$FormulaReviewCsv,

    [Parameter(Mandatory = $true)]
    [string]$OmmlCandidateCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$ReviewFileName,

    [string]$ReportPath,

    [ValidateRange(1, 100)]
    [int]$MaxItems = 10
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'PhysicsPpt.Common.ps1')

$script:NsA = 'http://schemas.openxmlformats.org/drawingml/2006/main'
$script:NsP = 'http://schemas.openxmlformats.org/presentationml/2006/main'
$script:NsMc = 'http://schemas.openxmlformats.org/markup-compatibility/2006'
$script:NsA14 = 'http://schemas.microsoft.com/office/drawing/2010/main'
$script:NsR = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'

# Apply-time whitelist re-validation: the scan-time match is never trusted on
# its own, so a stale or hand-edited review CSV cannot smuggle in a formula
# that the current config whitelist does not cover.
$script:FormulaWhitelist = Get-PhysicsPptFormulaWhitelist
if ($script:FormulaWhitelist.Count -eq 0) {
    Write-Warning "Formula whitelist is empty or unavailable; every candidate row will be rejected."
}

function Get-FormulaKey {
    param([object]$Row)
    $file = if ($null -ne $Row.PSObject.Properties['FilePath'] -and -not [string]::IsNullOrWhiteSpace([string]$Row.FilePath)) { [string]$Row.FilePath } else { [string]$Row.File }
    $slide = [string]$Row.Slide
    $shape = [string]$Row.Shape
    $formula = Get-NormalizedFormulaText -Text ([string]$Row.FormulaText)
    return "$file|$slide|$shape|$formula"
}

function Add-ReportRow {
    param(
        [System.Collections.Generic.List[object]]$Rows,
        [string]$File,
        [int]$Slide,
        [string]$Shape,
        [string]$Issue,
        [string]$Details
    )

    $Rows.Add([pscustomobject]@{
        Timestamp = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        File = $File
        Slide = $Slide
        Shape = $Shape
        Issue = $Issue
        Details = $Details
    }) | Out-Null
}

function Write-Report {
    param([System.Collections.Generic.List[object]]$Rows, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = $Rows | ConvertTo-Csv -NoTypeInformation
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

function Write-ZipEntryText {
    param(
        [System.IO.Compression.ZipArchive]$Zip,
        [string]$EntryName,
        [string]$Text
    )
    $entry = $Zip.GetEntry($EntryName)
    if ($null -ne $entry) { $entry.Delete() }
    $newEntry = $Zip.CreateEntry($EntryName, [System.IO.Compression.CompressionLevel]::Optimal)
    $stream = $null
    $writer = $null
    try {
    $stream = $newEntry.Open()
    # XML parts are written without BOM to match PowerPoint's own output;
    # Read-ZipEntryText detects either encoding on the read side.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $writer = New-Object System.IO.StreamWriter($stream, $utf8NoBom)
        $writer.Write($Text)
    } finally {
        if ($null -ne $writer) { $writer.Dispose() }
        if ($null -ne $stream) { $stream.Dispose() }
    }
}

function Convert-XmlDocumentToString {
    param([System.Xml.XmlDocument]$Document)
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Indent = $false
    $settings.OmitXmlDeclaration = $true
    $builder = New-Object System.Text.StringBuilder
    $writer = [System.Xml.XmlWriter]::Create($builder, $settings)
    try {
        $Document.Save($writer)
    } finally {
        if ($null -ne $writer) { $writer.Dispose() }
    }
    return "<?xml version=`"1.0`" encoding=`"UTF-8`" standalone=`"yes`"?>`r`n$($builder.ToString())"
}

function New-NamespaceManager {
    param([System.Xml.XmlDocument]$Document)
    $ns = New-Object System.Xml.XmlNamespaceManager($Document.NameTable)
    $ns.AddNamespace('a', $script:NsA) | Out-Null
    $ns.AddNamespace('p', $script:NsP) | Out-Null
    return ,$ns
}

function Get-SlidePartNameMap {
    <#
      Map 1-based presentation-order slide numbers to their zip part names.
      slideN.xml file numbers follow creation order, not presentation order,
      so this mapping must go through ppt/presentation.xml sldIdLst + rels.
    #>
    param([System.IO.Compression.ZipArchive]$Zip)
    $map = @{}
    $presText = Read-ZipEntryText -Zip $Zip -EntryName 'ppt/presentation.xml'
    $relsText = Read-ZipEntryText -Zip $Zip -EntryName 'ppt/_rels/presentation.xml.rels'
    if ([string]::IsNullOrWhiteSpace($presText) -or [string]::IsNullOrWhiteSpace($relsText)) { return $map }

    $presDoc = New-Object System.Xml.XmlDocument
    $presDoc.PreserveWhitespace = $false
    $presDoc.LoadXml($presText)
    $relsDoc = New-Object System.Xml.XmlDocument
    $relsDoc.PreserveWhitespace = $false
    $relsDoc.LoadXml($relsText)

    $relTargets = @{}
    foreach ($rel in $relsDoc.GetElementsByTagName('Relationship')) {
        $id = [string]$rel.GetAttribute('Id')
        if (-not [string]::IsNullOrWhiteSpace($id)) {
            $relTargets[$id] = [string]$rel.GetAttribute('Target')
        }
    }

    $index = 0
    foreach ($sldId in $presDoc.SelectNodes('//*[local-name()="sldId"]')) {
        $index++
        $rid = [string]$sldId.GetAttribute('id', $script:NsR)
        if ([string]::IsNullOrWhiteSpace($rid) -or -not $relTargets.ContainsKey($rid)) { continue }
        $target = Resolve-PackageTarget -SourcePart 'ppt/presentation.xml' -Target $relTargets[$rid]
        if ([string]::IsNullOrWhiteSpace($target)) { continue }
        $map[$index] = $target
    }
    return $map
}

function Get-ShapeText {
    param([System.Xml.XmlElement]$Shape, [System.Xml.XmlNamespaceManager]$NamespaceManager)
    $texts = New-Object System.Collections.Generic.List[string]
    foreach ($node in @($Shape.SelectNodes('.//a:t', $NamespaceManager))) {
        $texts.Add([string]$node.InnerText) | Out-Null
    }
    return ($texts -join '')
}

function Test-IsProtectedScopeShape {
    # Shapes inside groups (invariant: groups are never modified) and inside
    # mc:Fallback branches (writing there would corrupt fallback content).
    param([System.Xml.XmlElement]$Shape)
    $ancestor = $Shape.ParentNode
    while ($null -ne $ancestor) {
        if ($ancestor.LocalName -eq 'grpSp' -or $ancestor.LocalName -eq 'Fallback') { return $true }
        $ancestor = $ancestor.ParentNode
    }
    return $false
}

function Find-TargetShape {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlNamespaceManager]$NamespaceManager,
        [string]$ShapeName,
        [string]$FormulaText
    )
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    $fallback = $null
    $textMatches = New-Object System.Collections.Generic.List[object]
    foreach ($shape in @($Document.SelectNodes('//p:sp', $NamespaceManager))) {
        if (Test-IsProtectedScopeShape -Shape $shape) { continue }
        $shapeNorm = Get-NormalizedFormulaText -Text (Get-ShapeText -Shape $shape -NamespaceManager $NamespaceManager)
        $textHit = (-not [string]::IsNullOrWhiteSpace($formulaNorm) -and $shapeNorm.Contains($formulaNorm))
        $nameNode = $shape.SelectSingleNode('./p:nvSpPr/p:cNvPr', $NamespaceManager)
        $nameHit = ($null -ne $nameNode -and [string]$nameNode.GetAttribute('name') -eq $ShapeName)
        if ($textHit) {
            if ($nameHit) { return $shape }
            $textMatches.Add($shape) | Out-Null
        } elseif ($nameHit -and $null -eq $fallback) {
            $fallback = $shape
        }
    }
    # Default shape names are re-localized by PowerPoint on every save
    # ("TextBox 3" vs "文本框 3"), so the scan-time name may not survive
    # normalization; a unique formula-text match is still unambiguous.
    if ($textMatches.Count -eq 1) { return $textMatches[0] }
    return $fallback
}

function Find-ExactFormulaParagraph {
    param(
        [System.Xml.XmlElement]$Shape,
        [System.Xml.XmlNamespaceManager]$NamespaceManager,
        [string]$FormulaText
    )
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    foreach ($paragraph in @($Shape.SelectNodes('.//a:p', $NamespaceManager))) {
        $text = New-Object System.Collections.Generic.List[string]
        foreach ($textNode in @($paragraph.SelectNodes('.//a:t', $NamespaceManager))) {
            $text.Add([string]$textNode.InnerText) | Out-Null
        }
        $paragraphText = $text -join ''
        $paragraphNorm = Get-NormalizedFormulaText -Text $paragraphText
        if ($paragraphNorm -ceq $formulaNorm) {
            return $paragraph
        }
    }
    return $null
}

function Replace-ParagraphWithOmml {
    param(
        [System.Xml.XmlDocument]$SlideDocument,
        [System.Xml.XmlElement]$Paragraph,
        [string]$OmmlFragmentPath
    )
    $fragment = New-Object System.Xml.XmlDocument
    $fragment.PreserveWhitespace = $false
    $fragment.Load($OmmlFragmentPath)
    if ($null -eq $fragment.DocumentElement -or $fragment.DocumentElement.LocalName -ne 'm') {
        throw "Invalid OMML fragment root: $OmmlFragmentPath"
    }

    # Keep the paragraph's endParaRPr (paragraph-mark formatting, common in
    # Chinese decks) but re-append it after the math zone so the CT_TextParagraph
    # child order stays schema-valid: pPr, content, endParaRPr.
    $endParaRPr = $null
    foreach ($child in @($Paragraph.ChildNodes)) {
        if ($child.LocalName -eq 'endParaRPr' -and $child.NamespaceURI -eq $script:NsA) {
            $endParaRPr = $child
            continue
        }
        if ($child.LocalName -eq 'pPr' -and $child.NamespaceURI -eq $script:NsA) { continue }
        $Paragraph.RemoveChild($child) | Out-Null
    }

    $imported = $SlideDocument.ImportNode($fragment.DocumentElement, $true)
    $Paragraph.AppendChild($imported) | Out-Null
    if ($null -ne $endParaRPr) {
        $Paragraph.AppendChild($endParaRPr) | Out-Null
    }
}

function Wrap-ShapeInAlternateContent {
    param(
        [System.Xml.XmlDocument]$SlideDocument,
        [System.Xml.XmlElement]$Shape,
        [System.Xml.XmlNode]$FallbackShape
    )

    if ($Shape.ParentNode.LocalName -eq 'Choice' -and $Shape.ParentNode.NamespaceURI -eq $script:NsMc) {
        return
    }

    $parent = $Shape.ParentNode
    $alternate = $SlideDocument.CreateElement('mc', 'AlternateContent', $script:NsMc)
    $alternate.SetAttribute('xmlns:mc', $script:NsMc)
    $alternate.SetAttribute('xmlns:a14', $script:NsA14)

    $choice = $SlideDocument.CreateElement('mc', 'Choice', $script:NsMc)
    $choice.SetAttribute('Requires', 'a14')
    $choice.AppendChild($Shape.CloneNode($true)) | Out-Null

    $fallback = $SlideDocument.CreateElement('mc', 'Fallback', $script:NsMc)
    $fallback.AppendChild($FallbackShape.CloneNode($true)) | Out-Null

    $alternate.AppendChild($choice) | Out-Null
    $alternate.AppendChild($fallback) | Out-Null
    $parent.ReplaceChild($alternate, $Shape) | Out-Null
}

$InputPath = [System.IO.Path]::GetFullPath($InputPath)
$FormulaReviewCsv = [System.IO.Path]::GetFullPath($FormulaReviewCsv)
$OmmlCandidateCsv = [System.IO.Path]::GetFullPath($OmmlCandidateCsv)
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if ([string]::IsNullOrWhiteSpace($ReportPath)) {
    $ReportPath = Join-Path (Split-Path -Parent $OutputPath) 'formula-omml-apply-report.csv'
}
$ReportPath = [System.IO.Path]::GetFullPath($ReportPath)

if (-not (Test-Path -LiteralPath $InputPath)) { throw "InputPath not found: $InputPath" }
if (-not (Test-Path -LiteralPath $FormulaReviewCsv)) { throw "FormulaReviewCsv not found: $FormulaReviewCsv" }
if (-not (Test-Path -LiteralPath $OmmlCandidateCsv)) { throw "OmmlCandidateCsv not found: $OmmlCandidateCsv" }

$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
if ([string]::Equals($InputPath, $OutputPath, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "OutputPath must differ from InputPath; the source PPTX is never modified in place."
}
$reportDir = Split-Path -Parent $ReportPath
if (-not (Test-Path -LiteralPath $reportDir)) { New-Item -ItemType Directory -Path $reportDir -Force | Out-Null }

$inputFileName = [System.IO.Path]::GetFileName($InputPath)
$reviewFileNameForMatch = if ([string]::IsNullOrWhiteSpace($ReviewFileName)) { $inputFileName } else { [string]$ReviewFileName }
$reviewRows = @(
    Import-Csv -LiteralPath $FormulaReviewCsv -Encoding UTF8 |
        Where-Object {
            $_.SuggestedAction -eq 'ReviewWhitelistConversion' -and (
                ($null -ne $_.PSObject.Properties['FilePath'] -and $_.FilePath -eq $reviewFileNameForMatch) -or
                $_.File -eq $reviewFileNameForMatch
            )
        } |
        Select-Object -First $MaxItems
)
$candidateRows = @(Import-Csv -LiteralPath $OmmlCandidateCsv -Encoding UTF8 | Where-Object { $_.Status -eq 'Generated' })
$candidateByKey = @{}
foreach ($candidate in $candidateRows) {
    $candidateByKey[(Get-FormulaKey -Row $candidate)] = $candidate
}

$reportRows = New-Object System.Collections.Generic.List[object]
if ($reviewRows.Count -eq 0) {
    Add-ReportRow -Rows $reportRows -File $reviewFileNameForMatch -Slide 0 -Shape '(presentation)' -Issue 'NoFormulaWhitelistCandidate' -Details 'No matching ReviewWhitelistConversion rows found.'
    Write-Report -Rows $reportRows -Path $ReportPath
    Write-Host "Report saved: $ReportPath"
    return
}

Copy-Item -LiteralPath $InputPath -Destination $OutputPath -Force
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip = $null
try {
    $zip = [System.IO.Compression.ZipFile]::Open($OutputPath, [System.IO.Compression.ZipArchiveMode]::Update)
    $slidePartMap = Get-SlidePartNameMap -Zip $zip
    foreach ($row in $reviewRows) {
        if ([string]$row.Slide -notmatch '^\d+$') {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide 0 -Shape ([string]$row.Shape) -Issue 'FormulaRowInvalidSlide' -Details ("Slide='{0}'" -f $row.Slide)
            continue
        }
        $slideNo = [int]$row.Slide
        $shapeName = [string]$row.Shape

        # Apply-time whitelist re-validation against the current config; the
        # scan-time CSV is never trusted on its own (case-sensitive match).
        $rule = Test-FormulaWhitelistMatch -Text ([string]$row.FormulaText) -Whitelist $script:FormulaWhitelist
        if ($null -eq $rule) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaWhitelistRejected' -Details ("No case-sensitive whitelist match in current config for: {0}" -f $row.FormulaText)
            continue
        }

        $key = Get-FormulaKey -Row $row
        if (-not $candidateByKey.ContainsKey($key)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlCandidateMissing' -Details $key
            continue
        }

        $candidate = $candidateByKey[$key]
        $candidateSource = if ($null -ne $candidate.PSObject.Properties['TargetSource']) { [string]$candidate.TargetSource } else { '' }
        if ($candidateSource -ne 'CurrentConfig') {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaWhitelistRejected' -Details ("candidate TargetSource='{0}'; only CurrentConfig candidates may be applied." -f $candidateSource)
            continue
        }
        $ruleTarget = Get-FormulaRuleValue -Rule $rule -Name 'targetUnicodeMath'
        $candidateTarget = if ($null -ne $candidate.PSObject.Properties['TargetUnicodeMath']) { [string]$candidate.TargetUnicodeMath } else { '' }
        if (-not [string]::Equals($candidateTarget, $ruleTarget, [System.StringComparison]::Ordinal)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaWhitelistRejected' -Details ("candidate target '{0}' does not match current whitelist '{1}'." -f $candidateTarget, $ruleTarget)
            continue
        }

        $fragmentPath = [string]$candidate.OmmlFragment
        if ([string]::IsNullOrWhiteSpace($fragmentPath) -or -not (Test-Path -LiteralPath $fragmentPath)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlFragmentMissing' -Details $fragmentPath
            continue
        }

        if (-not $slidePartMap.ContainsKey($slideNo)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSlideXmlMissing' -Details ("no presentation-order slide part resolved for slide {0}" -f $slideNo)
            continue
        }
        $entryName = [string]$slidePartMap[$slideNo]
        $slideText = Read-ZipEntryText -Zip $zip -EntryName $entryName
        if ([string]::IsNullOrWhiteSpace($slideText)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSlideXmlMissing' -Details $entryName
            continue
        }

        try {
            $slideDoc = New-Object System.Xml.XmlDocument
            $slideDoc.PreserveWhitespace = $true
            $slideDoc.LoadXml($slideText)
            $ns = New-NamespaceManager -Document $slideDoc
            $shape = Find-TargetShape -Document $slideDoc -NamespaceManager $ns -ShapeName $shapeName -FormulaText ([string]$row.FormulaText)
            if ($null -eq $shape) {
                Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaShapeNotFound' -Details ([string]$row.FormulaText)
                continue
            }
            $fallbackShape = $shape.CloneNode($true)

            $paragraph = Find-ExactFormulaParagraph -Shape $shape -NamespaceManager $ns -FormulaText ([string]$row.FormulaText)
            if ($null -eq $paragraph) {
                Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaExactParagraphNotFound' -Details ([string]$row.FormulaText)
                continue
            }
            $unsafeNodes = @($paragraph.SelectNodes('.//a:fld', $ns)) + @($paragraph.SelectNodes('.//a:br', $ns))
            if ($unsafeNodes.Count -gt 0) {
                Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaParagraphUnsafeNodes' -Details 'Paragraph contains a:fld/a:br; conversion skipped for manual review.'
                continue
            }

            Replace-ParagraphWithOmml -SlideDocument $slideDoc -Paragraph $paragraph -OmmlFragmentPath $fragmentPath
            Wrap-ShapeInAlternateContent -SlideDocument $slideDoc -Shape $shape -FallbackShape $fallbackShape
            Write-ZipEntryText -Zip $zip -EntryName $entryName -Text (Convert-XmlDocumentToString -Document $slideDoc)
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlInserted' -Details ("fragment={0}; targetUnicodeMath={1}" -f $fragmentPath, $candidate.TargetUnicodeMath)
        } catch {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlInsertFailed' -Details $_.Exception.Message
        }
    }
} finally {
    if ($null -ne $zip) { $zip.Dispose() }
}

Add-ReportRow -Rows $reportRows -File $inputFileName -Slide 0 -Shape '(presentation)' -Issue 'SavedAs' -Details $OutputPath
Write-Report -Rows $reportRows -Path $ReportPath
Write-Host "Report saved: $ReportPath"
Write-Host "Output saved: $OutputPath"
