<#
.SYNOPSIS
  Apply reviewed formula whitelist candidates as OfficeMath/OMML in a copied PPTX.

.DESCRIPTION
  Reads formula-review.csv and formula-omml-candidates.csv, copies the source
  PPTX, replaces exact-match text formula paragraphs with a14:m/m:oMath
  fragments, and writes a report. The source PPTX is never modified.

.PARAMETER InputPath
  Source .pptx file.

.PARAMETER FormulaReviewCsv
  formula-review.csv generated by Invoke-PhysicsPptWorkflow.ps1.

.PARAMETER OmmlCandidateCsv
  formula-omml-candidates.csv generated by Export-FormulaOmmlCandidates.ps1.

.PARAMETER OutputPath
  New PPTX path to save.

.PARAMETER ReviewFileName
  Original PPTX file name used in formula-review.csv. Defaults to InputPath file name.

.PARAMETER ReportPath
  CSV report path. Defaults next to OutputPath.

.PARAMETER MaxItems
  Maximum whitelist rows to apply in one run. Defaults to 10.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$FormulaReviewCsv,

    [Parameter(Mandatory = $true)]
    [string]$OmmlCandidateCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$ReviewFileName,

    [string]$ReportPath,

    [ValidateRange(1, 100)]
    [int]$MaxItems = 10
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'PhysicsPpt.Common.ps1')

$script:NsA = 'http://schemas.openxmlformats.org/drawingml/2006/main'
$script:NsP = 'http://schemas.openxmlformats.org/presentationml/2006/main'
$script:NsMc = 'http://schemas.openxmlformats.org/markup-compatibility/2006'
$script:NsA14 = 'http://schemas.microsoft.com/office/drawing/2010/main'

function Get-NormalizedFormulaText {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return '' }
    return (($Text -replace '\s+', '') -replace '＝', '=').Trim()
}

function Get-FormulaKey {
    param([object]$Row)
    $file = if ($null -ne $Row.PSObject.Properties['FilePath'] -and -not [string]::IsNullOrWhiteSpace([string]$Row.FilePath)) { [string]$Row.FilePath } else { [string]$Row.File }
    $slide = [string]$Row.Slide
    $shape = [string]$Row.Shape
    $formula = Get-NormalizedFormulaText -Text ([string]$Row.FormulaText)
    return "$file|$slide|$shape|$formula"
}

function Add-ReportRow {
    param(
        [System.Collections.Generic.List[object]]$Rows,
        [string]$File,
        [int]$Slide,
        [string]$Shape,
        [string]$Issue,
        [string]$Details
    )

    $Rows.Add([pscustomobject]@{
        Timestamp = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        File = $File
        Slide = $Slide
        Shape = $Shape
        Issue = $Issue
        Details = $Details
    }) | Out-Null
}

function Write-Report {
    param([System.Collections.Generic.List[object]]$Rows, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = $Rows | ConvertTo-Csv -NoTypeInformation
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

function Write-ZipEntryText {
    param(
        [System.IO.Compression.ZipArchive]$Zip,
        [string]$EntryName,
        [string]$Text
    )
    $entry = $Zip.GetEntry($EntryName)
    if ($null -ne $entry) { $entry.Delete() }
    $newEntry = $Zip.CreateEntry($EntryName, [System.IO.Compression.CompressionLevel]::Optimal)
    $stream = $null
    $writer = $null
    try {
        $stream = $newEntry.Open()
        $utf8Bom = New-Object System.Text.UTF8Encoding($true)
        $writer = New-Object System.IO.StreamWriter($stream, $utf8Bom)
        $writer.Write($Text)
    } finally {
        if ($null -ne $writer) { $writer.Dispose() }
        if ($null -ne $stream) { $stream.Dispose() }
    }
}

function Convert-XmlDocumentToString {
    param([System.Xml.XmlDocument]$Document)
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Indent = $false
    $settings.OmitXmlDeclaration = $true
    $builder = New-Object System.Text.StringBuilder
    $writer = [System.Xml.XmlWriter]::Create($builder, $settings)
    try {
        $Document.Save($writer)
    } finally {
        if ($null -ne $writer) { $writer.Dispose() }
    }
    return "<?xml version=`"1.0`" encoding=`"UTF-8`" standalone=`"yes`"?>`r`n$($builder.ToString())"
}

function New-NamespaceManager {
    param([System.Xml.XmlDocument]$Document)
    $ns = New-Object System.Xml.XmlNamespaceManager($Document.NameTable)
    $ns.AddNamespace('a', $script:NsA) | Out-Null
    $ns.AddNamespace('p', $script:NsP) | Out-Null
    return ,$ns
}

function Get-ShapeText {
    param([System.Xml.XmlElement]$Shape, [System.Xml.XmlNamespaceManager]$NamespaceManager)
    $texts = New-Object System.Collections.Generic.List[string]
    foreach ($node in @($Shape.SelectNodes('.//a:t', $NamespaceManager))) {
        $texts.Add([string]$node.InnerText) | Out-Null
    }
    return ($texts -join '')
}

function Find-TargetShape {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlNamespaceManager]$NamespaceManager,
        [string]$ShapeName,
        [string]$FormulaText
    )
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    $fallback = $null
    foreach ($shape in @($Document.SelectNodes('//p:sp', $NamespaceManager))) {
        $nameNode = $shape.SelectSingleNode('./p:nvSpPr/p:cNvPr', $NamespaceManager)
        if ($null -eq $nameNode -or [string]$nameNode.GetAttribute('name') -ne $ShapeName) { continue }
        if ($null -eq $fallback) { $fallback = $shape }
        $shapeNorm = Get-NormalizedFormulaText -Text (Get-ShapeText -Shape $shape -NamespaceManager $NamespaceManager)
        if (-not [string]::IsNullOrWhiteSpace($formulaNorm) -and $shapeNorm.Contains($formulaNorm)) {
            return $shape
        }
    }
    return $fallback
}

function Find-ExactFormulaParagraph {
    param(
        [System.Xml.XmlElement]$Shape,
        [System.Xml.XmlNamespaceManager]$NamespaceManager,
        [string]$FormulaText
    )
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    foreach ($paragraph in @($Shape.SelectNodes('.//a:p', $NamespaceManager))) {
        $text = New-Object System.Collections.Generic.List[string]
        foreach ($textNode in @($paragraph.SelectNodes('.//a:t', $NamespaceManager))) {
            $text.Add([string]$textNode.InnerText) | Out-Null
        }
        $paragraphText = $text -join ''
        $paragraphNorm = Get-NormalizedFormulaText -Text $paragraphText
        if ($paragraphNorm -eq $formulaNorm) {
            return $paragraph
        }
    }
    return $null
}

function Replace-ParagraphWithOmml {
    param(
        [System.Xml.XmlDocument]$SlideDocument,
        [System.Xml.XmlElement]$Paragraph,
        [string]$OmmlFragmentPath
    )
    $fragment = New-Object System.Xml.XmlDocument
    $fragment.PreserveWhitespace = $false
    $fragment.Load($OmmlFragmentPath)
    if ($null -eq $fragment.DocumentElement -or $fragment.DocumentElement.LocalName -ne 'm') {
        throw "Invalid OMML fragment root: $OmmlFragmentPath"
    }

    foreach ($child in @($Paragraph.ChildNodes)) {
        if ($child.LocalName -eq 'pPr' -and $child.NamespaceURI -eq $script:NsA) { continue }
        $Paragraph.RemoveChild($child) | Out-Null
    }

    $imported = $SlideDocument.ImportNode($fragment.DocumentElement, $true)
    $Paragraph.AppendChild($imported) | Out-Null
}

function Wrap-ShapeInAlternateContent {
    param(
        [System.Xml.XmlDocument]$SlideDocument,
        [System.Xml.XmlElement]$Shape,
        [System.Xml.XmlNode]$FallbackShape
    )

    if ($Shape.ParentNode.LocalName -eq 'Choice' -and $Shape.ParentNode.NamespaceURI -eq $script:NsMc) {
        return
    }

    $parent = $Shape.ParentNode
    $alternate = $SlideDocument.CreateElement('mc', 'AlternateContent', $script:NsMc)
    $alternate.SetAttribute('xmlns:mc', $script:NsMc)
    $alternate.SetAttribute('xmlns:a14', $script:NsA14)

    $choice = $SlideDocument.CreateElement('mc', 'Choice', $script:NsMc)
    $choice.SetAttribute('Requires', 'a14')
    $choice.AppendChild($Shape.CloneNode($true)) | Out-Null

    $fallback = $SlideDocument.CreateElement('mc', 'Fallback', $script:NsMc)
    $fallback.AppendChild($FallbackShape.CloneNode($true)) | Out-Null

    $alternate.AppendChild($choice) | Out-Null
    $alternate.AppendChild($fallback) | Out-Null
    $parent.ReplaceChild($alternate, $Shape) | Out-Null
}

$InputPath = [System.IO.Path]::GetFullPath($InputPath)
$FormulaReviewCsv = [System.IO.Path]::GetFullPath($FormulaReviewCsv)
$OmmlCandidateCsv = [System.IO.Path]::GetFullPath($OmmlCandidateCsv)
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if ([string]::IsNullOrWhiteSpace($ReportPath)) {
    $ReportPath = Join-Path (Split-Path -Parent $OutputPath) 'formula-omml-apply-report.csv'
}
$ReportPath = [System.IO.Path]::GetFullPath($ReportPath)

if (-not (Test-Path -LiteralPath $InputPath)) { throw "InputPath not found: $InputPath" }
if (-not (Test-Path -LiteralPath $FormulaReviewCsv)) { throw "FormulaReviewCsv not found: $FormulaReviewCsv" }
if (-not (Test-Path -LiteralPath $OmmlCandidateCsv)) { throw "OmmlCandidateCsv not found: $OmmlCandidateCsv" }

$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
$reportDir = Split-Path -Parent $ReportPath
if (-not (Test-Path -LiteralPath $reportDir)) { New-Item -ItemType Directory -Path $reportDir -Force | Out-Null }

$inputFileName = [System.IO.Path]::GetFileName($InputPath)
$reviewFileNameForMatch = if ([string]::IsNullOrWhiteSpace($ReviewFileName)) { $inputFileName } else { [string]$ReviewFileName }
$reviewRows = @(
    Import-Csv -LiteralPath $FormulaReviewCsv -Encoding UTF8 |
        Where-Object {
            $_.SuggestedAction -eq 'ReviewWhitelistConversion' -and (
                ($null -ne $_.PSObject.Properties['FilePath'] -and $_.FilePath -eq $reviewFileNameForMatch) -or
                $_.File -eq $reviewFileNameForMatch
            )
        } |
        Select-Object -First $MaxItems
)
$candidateRows = @(Import-Csv -LiteralPath $OmmlCandidateCsv -Encoding UTF8 | Where-Object { $_.Status -eq 'Generated' })
$candidateByKey = @{}
foreach ($candidate in $candidateRows) {
    $candidateByKey[(Get-FormulaKey -Row $candidate)] = $candidate
}

$reportRows = New-Object System.Collections.Generic.List[object]
if ($reviewRows.Count -eq 0) {
    Add-ReportRow -Rows $reportRows -File $reviewFileNameForMatch -Slide 0 -Shape '(presentation)' -Issue 'NoFormulaWhitelistCandidate' -Details 'No matching ReviewWhitelistConversion rows found.'
    Write-Report -Rows $reportRows -Path $ReportPath
    Write-Host "Report saved: $ReportPath"
    return
}

Copy-Item -LiteralPath $InputPath -Destination $OutputPath -Force
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip = $null
try {
    $zip = [System.IO.Compression.ZipFile]::Open($OutputPath, [System.IO.Compression.ZipArchiveMode]::Update)
    foreach ($row in $reviewRows) {
        $slideNo = [int]$row.Slide
        $shapeName = [string]$row.Shape
        $key = Get-FormulaKey -Row $row
        if (-not $candidateByKey.ContainsKey($key)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlCandidateMissing' -Details $key
            continue
        }

        $candidate = $candidateByKey[$key]
        $fragmentPath = [string]$candidate.OmmlFragment
        if ([string]::IsNullOrWhiteSpace($fragmentPath) -or -not (Test-Path -LiteralPath $fragmentPath)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlFragmentMissing' -Details $fragmentPath
            continue
        }

        $entryName = "ppt/slides/slide$slideNo.xml"
        $slideText = Read-ZipEntryText -Zip $zip -EntryName $entryName
        if ([string]::IsNullOrWhiteSpace($slideText)) {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSlideXmlMissing' -Details $entryName
            continue
        }

        try {
            $slideDoc = New-Object System.Xml.XmlDocument
            $slideDoc.PreserveWhitespace = $true
            $slideDoc.LoadXml($slideText)
            $ns = New-NamespaceManager -Document $slideDoc
            $shape = Find-TargetShape -Document $slideDoc -NamespaceManager $ns -ShapeName $shapeName -FormulaText ([string]$row.FormulaText)
            if ($null -eq $shape) {
                Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaShapeNotFound' -Details ([string]$row.FormulaText)
                continue
            }
            $fallbackShape = $shape.CloneNode($true)

            $paragraph = Find-ExactFormulaParagraph -Shape $shape -NamespaceManager $ns -FormulaText ([string]$row.FormulaText)
            if ($null -eq $paragraph) {
                Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaExactParagraphNotFound' -Details ([string]$row.FormulaText)
                continue
            }

            Replace-ParagraphWithOmml -SlideDocument $slideDoc -Paragraph $paragraph -OmmlFragmentPath $fragmentPath
            Wrap-ShapeInAlternateContent -SlideDocument $slideDoc -Shape $shape -FallbackShape $fallbackShape
            Write-ZipEntryText -Zip $zip -EntryName $entryName -Text (Convert-XmlDocumentToString -Document $slideDoc)
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlInserted' -Details ("fragment={0}; targetUnicodeMath={1}" -f $fragmentPath, $candidate.TargetUnicodeMath)
        } catch {
            Add-ReportRow -Rows $reportRows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaOmmlInsertFailed' -Details $_.Exception.Message
        }
    }
} finally {
    if ($null -ne $zip) { $zip.Dispose() }
}

Add-ReportRow -Rows $reportRows -File $inputFileName -Slide 0 -Shape '(presentation)' -Issue 'SavedAs' -Details $OutputPath
Write-Report -Rows $reportRows -Path $ReportPath
Write-Host "Report saved: $ReportPath"
Write-Host "Output saved: $OutputPath"
