<#
.SYNOPSIS
  Replace reviewed Equation OLE objects with native OfficeMath/OMML shapes in a copied PPTX.

.DESCRIPTION
  Reads a mapping CSV (slide + global OLE index from the formula OLE inventory) and an
  OMML candidates CSV generated by Export-FormulaOmmlCandidates.ps1, copies the source
  PPTX, and swaps each targeted Equation.* OLE graphicFrame for an mc:AlternateContent
  whose Choice is a bounds-preserving text shape carrying the a14:m/m:oMath fragment and
  whose Fallback keeps the original OLE graphicFrame(s) verbatim for older viewers.
  Run properties are restyled to the deck's native math convention (m:nor, role-based
  italic posture, configured fonts, main/subscript colors, explicit size). The source PPTX
  is never modified.

.PARAMETER InputPath
  Source .pptx file.

.PARAMETER MappingCsv
  CSV with columns: Slide,OleIndex,WhitelistName,SizePt,MainColorHex,SubColorHex,Note.
  OleIndex is the global zero-based OLE index from the inventory ordering
  (slide ascending, then y, then x); use semicolons to merge OLEs into one formula.

.PARAMETER OmmlCandidateCsv
  formula-omml-candidates.csv generated by Export-FormulaOmmlCandidates.ps1.

.PARAMETER OutputPath
  New PPTX path to save.

.PARAMETER ReportPath
  CSV report path. Defaults next to OutputPath.

.PARAMETER MathFontName
  Latin/math font applied to formula runs. Defaults to Cambria Math.

.PARAMETER EastAsianFontName
  East Asian font applied to Chinese formula runs and subscripts. Defaults to 微软雅黑.

.PARAMETER MaxItems
  Maximum mapping rows to apply in one run. Defaults to 20.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$MappingCsv,

    [Parameter(Mandatory = $true)]
    [string]$OmmlCandidateCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$ReportPath,

    [string]$MathFontName = 'Cambria Math',

    [string]$EastAsianFontName = '',

    [ValidateRange(1, 100)]
    [int]$MaxItems = 20
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'PhysicsPpt.Common.ps1')

if ([string]::IsNullOrWhiteSpace($EastAsianFontName)) {
    $styleConfigPath = Join-Path (Split-Path -Parent $PSScriptRoot) 'config\physics-ppt-style.config.json'
    if (Test-Path -LiteralPath $styleConfigPath) {
        try {
            $styleConfig = Get-Content -LiteralPath $styleConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json
            if ($null -ne $styleConfig.fonts.mathEastAsian -and -not [string]::IsNullOrWhiteSpace([string]$styleConfig.fonts.mathEastAsian)) {
                $EastAsianFontName = [string]$styleConfig.fonts.mathEastAsian
            }
        } catch {
            throw "Formula style config could not be loaded: $($_.Exception.Message)"
        }
    }
}
if ([string]::IsNullOrWhiteSpace($EastAsianFontName)) { $EastAsianFontName = '宋体' }

$script:NsA14 = 'http://schemas.microsoft.com/office/drawing/2010/main'
$script:NsA = 'http://schemas.openxmlformats.org/drawingml/2006/main'
$script:NsM = 'http://schemas.openxmlformats.org/officeDocument/2006/math'
$script:NsP = 'http://schemas.openxmlformats.org/presentationml/2006/main'
$script:NsMc = 'http://schemas.openxmlformats.org/markup-compatibility/2006'

function Add-ReportRow {
    param($Rows, [string]$File, [int]$Slide, [string]$Shape, [string]$Issue, [string]$Details)
    $Rows.Add([pscustomobject]@{
        File = $File
        Slide = $Slide
        Shape = $Shape
        Issue = $Issue
        Details = $Details
    }) | Out-Null
}

function Write-Report {
    param($Rows, [string]$Path)
    $parent = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($parent) -and -not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = @($Rows | ConvertTo-Csv -NoTypeInformation | ForEach-Object { [string]$_ })
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

function Write-ZipEntryText {
    param($Zip, [string]$EntryName, [string]$Text)
    $entry = $Zip.GetEntry($EntryName)
    if ($null -eq $entry) { throw "Zip entry not found: $EntryName" }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $bytes = $utf8NoBom.GetBytes($Text)
    $entry.Delete() | Out-Null
    $newEntry = $Zip.CreateEntry($EntryName)
    $stream = $newEntry.Open()
    try {
        $stream.Write($bytes, 0, $bytes.Length)
    } finally {
        $stream.Dispose()
    }
}

function New-NamespaceManager {
    param([System.Xml.XmlDocument]$Document)
    $ns = New-Object System.Xml.XmlNamespaceManager($Document.NameTable)
    $ns.AddNamespace('a', $script:NsA)
    $ns.AddNamespace('a14', $script:NsA14)
    $ns.AddNamespace('m', $script:NsM)
    $ns.AddNamespace('p', $script:NsP)
    $ns.AddNamespace('mc', $script:NsMc)
    # Comma guards against PowerShell unrolling the IEnumerable manager into NameTable strings.
    return ,$ns
}

function Get-SlidePartNameMap {
    param($Zip)
    $presEntry = $Zip.GetEntry('ppt/presentation.xml')
    if ($null -eq $presEntry) { throw 'ppt/presentation.xml missing' }
    $reader = New-Object System.IO.StreamReader($presEntry.Open(), [System.Text.Encoding]::UTF8)
    $presText = $reader.ReadToEnd()
    $reader.Dispose()
    $relsEntry = $Zip.GetEntry('ppt/_rels/presentation.xml.rels')
    $reader = New-Object System.IO.StreamReader($relsEntry.Open(), [System.Text.Encoding]::UTF8)
    $relsText = $reader.ReadToEnd()
    $reader.Dispose()
    $ridToPart = @{}
    foreach ($match in [regex]::Matches($relsText, 'Id="(rId\d+)"[^>]*Target="(slides/slide\d+\.xml)"')) {
        $ridToPart[$match.Groups[1].Value] = 'ppt/' + $match.Groups[2].Value
    }
    $map = @{}
    $order = 0
    foreach ($match in [regex]::Matches($presText, '<p:sldId[^>]*r:id="(rId\d+)"')) {
        $order++
        $rid = $match.Groups[1].Value
        if ($ridToPart.ContainsKey($rid)) { $map[$order] = $ridToPart[$rid] }
    }
    return $map
}

function Test-IsProtectedScopeNode {
    # Shapes inside groups (invariant: groups are never modified) and inside
    # mc:Fallback branches must never become replacement targets.
    param([System.Xml.XmlElement]$Node)
    $ancestor = $Node.ParentNode
    while ($null -ne $ancestor) {
        if ($ancestor.LocalName -eq 'grpSp' -or $ancestor.LocalName -eq 'Fallback') { return $true }
        $ancestor = $ancestor.ParentNode
    }
    return $false
}

function Get-OleInventory {
    # Deterministic global OLE ordering: presentation-order slide ascending,
    # then y, then x. Must stay in sync with the inventory that produced the
    # mapping CSV (Export-FormulaOleInventory ordering).
    param($Zip, [hashtable]$DocsByPart, [hashtable]$NssByPart)
    $slidePartMap = Get-SlidePartNameMap -Zip $Zip
    $inventory = New-Object System.Collections.Generic.List[object]
    foreach ($slideNo in ($slidePartMap.Keys | Sort-Object)) {
        $entryName = [string]$slidePartMap[$slideNo]
        $doc = New-Object System.Xml.XmlDocument
        $doc.PreserveWhitespace = $true
        $doc.LoadXml((Read-ZipEntryText -Zip $Zip -EntryName $entryName))
        $ns = New-NamespaceManager -Document $doc
        $DocsByPart[$entryName] = $doc
        $NssByPart[$entryName] = $ns
        # Target OLE blocks at spTree level only. PowerPoint 2016+ stores each
        # equation OLE as a top-level mc:AlternateContent (graphicFrame lives in
        # a branch); older files may expose a bare graphicFrame. Anything deeper
        # (inside graphicData/Fallback) is not a block boundary and must never
        # receive a replacement.
        foreach ($spTree in @($doc.SelectNodes('//p:spTree', $ns))) {
            foreach ($child in @($spTree.ChildNodes)) {
                if ($child.NodeType -ne [System.Xml.XmlNodeType]::Element) { continue }
                $isBlock = ($child.LocalName -eq 'AlternateContent' -or $child.LocalName -eq 'graphicFrame')
                if (-not $isBlock) { continue }
                if (Test-IsProtectedScopeNode -Node $child) { continue }
                if ($null -ne $child.SelectSingleNode('.//p:cNvPr[contains(@name, "FormulaOmml")]', $ns)) { continue }
                $oleObj = $child.SelectSingleNode('.//p:oleObj', $ns)
                if ($null -eq $oleObj) { continue }
                $xfrm = $child.SelectSingleNode('.//p:xfrm', $ns)
                if ($null -eq $xfrm) { continue }
                $off = $xfrm.SelectSingleNode('./a:off', $ns)
                $ext = $xfrm.SelectSingleNode('./a:ext', $ns)
                if ($null -eq $off -or $null -eq $ext) { continue }
                $inventory.Add([pscustomobject]@{
                    Slide = [int]$slideNo
                    Part = $entryName
                    Node = $child
                    ProgId = [string]$oleObj.GetAttribute('progId')
                    X = [int64]$off.GetAttribute('x')
                    Y = [int64]$off.GetAttribute('y')
                    Cx = [int64]$ext.GetAttribute('cx')
                    Cy = [int64]$ext.GetAttribute('cy')
                }) | Out-Null
            }
        }
    }
    $sorted = @($inventory | Sort-Object -Property Slide, Y, X)
    for ($i = 0; $i -lt $sorted.Count; $i++) { $sorted[$i] | Add-Member -NotePropertyName Index -NotePropertyValue $i -Force }
    return $sorted
}

function Get-OmmlRunRole {
    param([string]$Text)
    if ([string]$Text -cmatch '^[0-9]+(?:\.[0-9]+)?$') { return 'Number' }
    if ([string]$Text -cmatch '^[\u3400-\u9FFF]$') { return 'Chinese' }
    if ([string]$Text -cmatch '^[A-Za-z]+$' -or [string]$Text -cmatch '^[\u0370-\u03FF]$') {
        if ([string]$Text -in @('J', 'kg', 'Pa', 'N', 'W', 'Hz', '℃')) { return 'Unit' }
        return 'Variable'
    }
    if ([string]$Text -in @('+', '-', '−', '×', '⋅', '∙', '*', '=', ',', '.', '(', ')', '<', '>', '≤', '≥')) { return 'Operator' }
    return 'Text'
}

function Convert-OmmlFragmentDocument {
    # Restyle an exporter fragment to the deck-native math convention.  The
    # source MathType formulas use a heavy display style, but only variables
    # are italic; operators, numbers, units, and Chinese subscripts stay
    # upright.  Chinese subscripts are reduced so they do not overflow the
    # original OLE bounds when PowerPoint renders the OMML text shape.
    param(
        [string]$FragmentPath,
        [int]$SizePt,
        [string]$MainHex,
        [string]$SubHex,
        [string]$FontName,
        [string]$EastAsianFontName,
        [string]$AccentHex,
        [string]$AccentTokens
    )
    $frag = New-Object System.Xml.XmlDocument
    $frag.PreserveWhitespace = $false
    $frag.Load($FragmentPath)
    $ns = New-NamespaceManager -Document $frag

    foreach ($run in @($frag.SelectNodes('//m:r', $ns))) {
        $mRPr = $run.SelectSingleNode('./m:rPr', $ns)
        if ($null -eq $mRPr) {
            $mRPr = $frag.CreateElement('m', 'rPr', $script:NsM)
            $null = $run.PrependChild($mRPr)
        }
        if ($null -eq $mRPr.SelectSingleNode('./m:nor', $ns)) {
            $nor = $frag.CreateElement('m', 'nor', $script:NsM)
            $null = $mRPr.PrependChild($nor)
        }
        $aRPr = $run.SelectSingleNode('./a:rPr', $ns)
        if ($null -eq $aRPr) {
            $aRPr = $frag.CreateElement('a', 'rPr', $script:NsA)
            $null = $run.InsertAfter($aRPr, $mRPr)
        }
        $runTextNode = $run.SelectSingleNode('./m:t', $ns)
        $runText = if ($null -ne $runTextNode) { [string]$runTextNode.InnerText } else { '' }
        $role = Get-OmmlRunRole -Text $runText

        $isSubscript = $false
        $ancestor = $run.ParentNode
        while ($null -ne $ancestor -and $ancestor.NodeType -ne [System.Xml.XmlNodeType]::Document) {
            if ($ancestor.LocalName -eq 'sub' -and $ancestor.NamespaceURI -eq $script:NsM) { $isSubscript = $true; break }
            $ancestor = $ancestor.ParentNode
        }

        $aRPr.SetAttribute('lang', $(if ($role -in @('Chinese', 'Text')) { 'zh-CN' } else { 'en-US' }))
        $aRPr.SetAttribute('altLang', $(if ($role -in @('Chinese', 'Text')) { 'en-US' } else { 'zh-CN' }))
        $runSize = $SizePt * 100
        if ($isSubscript) { $runSize = [Math]::Max(800, [int][Math]::Round($runSize * 0.72)) }
        $aRPr.SetAttribute('sz', ([string]$runSize))
        # MathType's Chinese subscripts and operators are upright regular glyphs;
        # forcing every OMML run bold makes the replacement wider than the
        # original OLE tight box (especially Q_放 / Q_吸). Keep the variable
        # posture role-based, but preserve regular weight for every run.
        $aRPr.SetAttribute('b', '0')
        $aRPr.SetAttribute('i', $(if ($role -eq 'Variable') { '1' } else { '0' }))

        $hex = $MainHex
        if ($isSubscript -and -not [string]::IsNullOrWhiteSpace($SubHex)) {
            $hex = $SubHex
        } elseif (-not [string]::IsNullOrWhiteSpace($AccentHex) -and
            @($AccentTokens -split ';' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }) -contains $runText) {
            $hex = $AccentHex
        }

        $oldFill = $aRPr.SelectSingleNode('./a:solidFill', $ns)
        if ($null -ne $oldFill) { $null = $aRPr.RemoveChild($oldFill) }
        $fill = $frag.CreateElement('a', 'solidFill', $script:NsA)
        $clr = $frag.CreateElement('a', 'srgbClr', $script:NsA)
        $clr.SetAttribute('val', $hex)
        $null = $fill.AppendChild($clr)
        $latin = $aRPr.SelectSingleNode('./a:latin', $ns)
        if ($null -ne $latin) {
            $null = $aRPr.InsertBefore($fill, $latin)
        } else {
            $null = $aRPr.AppendChild($fill)
            $latin = $frag.CreateElement('a', 'latin', $script:NsA)
            $null = $aRPr.AppendChild($latin)
        }
        $latin.SetAttribute('typeface', $FontName)
        $ea = $aRPr.SelectSingleNode('./a:ea', $ns)
        if ($null -eq $ea) {
            $ea = $frag.CreateElement('a', 'ea', $script:NsA)
            $null = $aRPr.InsertAfter($ea, $latin)
        }
        $ea.SetAttribute('typeface', $EastAsianFontName)
    }

    # Fraction bars and other structure take their color/size from m:ctrlPr/a:rPr.
    foreach ($ctrlPr in @($frag.SelectNodes('//m:ctrlPr', $ns))) {
        $ctrlRPr = $ctrlPr.SelectSingleNode('./a:rPr', $ns)
        if ($null -eq $ctrlRPr) {
            $ctrlRPr = $frag.CreateElement('a', 'rPr', $script:NsA)
            $null = $ctrlPr.AppendChild($ctrlRPr)
        }
        $ctrlRPr.SetAttribute('lang', 'en-US')
        $ctrlRPr.SetAttribute('altLang', 'zh-CN')
        $ctrlRPr.SetAttribute('sz', ([string]($SizePt * 100)))
        $ctrlRPr.SetAttribute('b', '0')
        $ctrlRPr.SetAttribute('i', '0')
        $oldFill = $ctrlRPr.SelectSingleNode('./a:solidFill', $ns)
        if ($null -ne $oldFill) { $null = $ctrlRPr.RemoveChild($oldFill) }
        $fill = $frag.CreateElement('a', 'solidFill', $script:NsA)
        $clr = $frag.CreateElement('a', 'srgbClr', $script:NsA)
        $clr.SetAttribute('val', $MainHex)
        $null = $fill.AppendChild($clr)
        # CT_TextCharacterProperties sequence: fill must precede latin/ea.
        $ctrlLatin = $ctrlRPr.SelectSingleNode('./a:latin', $ns)
        if ($null -ne $ctrlLatin) {
            $null = $ctrlRPr.InsertBefore($fill, $ctrlLatin)
        } else {
            $null = $ctrlRPr.AppendChild($fill)
        }
        $ctrlLatin = $ctrlRPr.SelectSingleNode('./a:latin', $ns)
        if ($null -eq $ctrlLatin) {
            $ctrlLatin = $frag.CreateElement('a', 'latin', $script:NsA)
            $null = $ctrlRPr.AppendChild($ctrlLatin)
        }
        $ctrlLatin.SetAttribute('typeface', $FontName)
        $ctrlEa = $ctrlRPr.SelectSingleNode('./a:ea', $ns)
        if ($null -eq $ctrlEa) {
            $ctrlEa = $frag.CreateElement('a', 'ea', $script:NsA)
            $null = $ctrlRPr.AppendChild($ctrlEa)
        }
        $ctrlEa.SetAttribute('typeface', $EastAsianFontName)
    }
    # XmlDocument is IEnumerable too; the comma keeps the document intact.
    return ,$frag
}

function New-OleReplacementAlternateContent {
    # Choice = bounds-preserving text shape with the OMML fragment;
    # Fallback = the original OLE graphicFrame(s), byte-identical clones.
    param(
        [System.Xml.XmlDocument]$SlideDocument,
        [System.Xml.XmlNamespaceManager]$NamespaceManager,
        $Targets,
        [System.Xml.XmlDocument]$FragmentDoc,
        [string]$ShapeName,
        [int]$NewId
    )
    $minX = [int64]::MaxValue; $minY = [int64]::MaxValue
    $maxX = [int64]::MinValue; $maxY = [int64]::MinValue
    foreach ($target in $Targets) {
        if ([int64]$target.X -lt $minX) { $minX = [int64]$target.X }
        if ([int64]$target.Y -lt $minY) { $minY = [int64]$target.Y }
        if ([int64]($target.X + $target.Cx) -gt $maxX) { $maxX = [int64]($target.X + $target.Cx) }
        if ([int64]($target.Y + $target.Cy) -gt $maxY) { $maxY = [int64]($target.Y + $target.Cy) }
    }

    $alternate = $SlideDocument.CreateElement('mc', 'AlternateContent', $script:NsMc)
    $null = $alternate.SetAttribute('xmlns:a14', $script:NsA14)
    $choice = $SlideDocument.CreateElement('mc', 'Choice', $script:NsMc)
    $null = $choice.SetAttribute('Requires', 'a14')

    $sp = $SlideDocument.CreateElement('p', 'sp', $script:NsP)
    $nvSpPr = $SlideDocument.CreateElement('p', 'nvSpPr', $script:NsP)
    $cNvPr = $SlideDocument.CreateElement('p', 'cNvPr', $script:NsP)
    $null = $cNvPr.SetAttribute('id', ([string]$NewId))
    $null = $cNvPr.SetAttribute('name', $ShapeName)
    $null = $nvSpPr.AppendChild($cNvPr)
    $null = $nvSpPr.AppendChild($SlideDocument.CreateElement('p', 'cNvSpPr', $script:NsP))
    $null = $nvSpPr.AppendChild($SlideDocument.CreateElement('p', 'nvPr', $script:NsP))
    $null = $sp.AppendChild($nvSpPr)

    $spPr = $SlideDocument.CreateElement('p', 'spPr', $script:NsP)
    $xfrm = $SlideDocument.CreateElement('a', 'xfrm', $script:NsA)
    $off = $SlideDocument.CreateElement('a', 'off', $script:NsA)
    $null = $off.SetAttribute('x', ([string]$minX))
    $null = $off.SetAttribute('y', ([string]$minY))
    $ext = $SlideDocument.CreateElement('a', 'ext', $script:NsA)
    $null = $ext.SetAttribute('cx', ([string]($maxX - $minX)))
    $null = $ext.SetAttribute('cy', ([string]($maxY - $minY)))
    $null = $xfrm.AppendChild($off)
    $null = $xfrm.AppendChild($ext)
    $null = $spPr.AppendChild($xfrm)
    $prstGeom = $SlideDocument.CreateElement('a', 'prstGeom', $script:NsA)
    $null = $prstGeom.SetAttribute('prst', 'rect')
    $null = $prstGeom.AppendChild($SlideDocument.CreateElement('a', 'avLst', $script:NsA))
    $null = $spPr.AppendChild($prstGeom)
    $null = $spPr.AppendChild($SlideDocument.CreateElement('a', 'noFill', $script:NsA))
    $ln = $SlideDocument.CreateElement('a', 'ln', $script:NsA)
    $null = $ln.AppendChild($SlideDocument.CreateElement('a', 'noFill', $script:NsA))
    $null = $spPr.AppendChild($ln)
    $null = $sp.AppendChild($spPr)

    $txBody = $SlideDocument.CreateElement('p', 'txBody', $script:NsP)
    $bodyPr = $SlideDocument.CreateElement('a', 'bodyPr', $script:NsA)
    $null = $bodyPr.SetAttribute('wrap', 'square')
    $null = $bodyPr.SetAttribute('lIns', '0')
    $null = $bodyPr.SetAttribute('tIns', '0')
    $null = $bodyPr.SetAttribute('rIns', '0')
    $null = $bodyPr.SetAttribute('bIns', '0')
    $null = $bodyPr.SetAttribute('anchor', 'ctr')
    $null = $bodyPr.SetAttribute('rtlCol', '0')
    # Native OMML glyph metrics can be a few percent wider than the original
    # MathType OLE bitmap. Normal autofit keeps the original tight box and
    # applies only the minimum shrink needed for a converted segment.
    $null = $bodyPr.AppendChild($SlideDocument.CreateElement('a', 'normAutofit', $script:NsA))
    $null = $txBody.AppendChild($bodyPr)
    $null = $txBody.AppendChild($SlideDocument.CreateElement('a', 'lstStyle', $script:NsA))
    $para = $SlideDocument.CreateElement('a', 'p', $script:NsA)
    $pPr = $SlideDocument.CreateElement('a', 'pPr', $script:NsA)
    $null = $pPr.SetAttribute('algn', 'ctr')
    $null = $para.AppendChild($pPr)
    $null = $para.AppendChild($SlideDocument.ImportNode($FragmentDoc.DocumentElement, $true))
    $null = $txBody.AppendChild($para)
    $null = $sp.AppendChild($txBody)
    $null = $choice.AppendChild($sp)
    $null = $alternate.AppendChild($choice)

    $fallback = $SlideDocument.CreateElement('mc', 'Fallback', $script:NsMc)
    foreach ($target in $Targets) {
        $null = $fallback.AppendChild($target.Node.CloneNode($true))
    }
    $null = $alternate.AppendChild($fallback)

    $parent = $Targets[0].Node.ParentNode
    $null = $parent.ReplaceChild($alternate, $Targets[0].Node)
    for ($i = 1; $i -lt $Targets.Count; $i++) {
        $null = $parent.RemoveChild($Targets[$i].Node)
    }
    return $alternate
}

function Convert-XmlDocumentToString {
    param([System.Xml.XmlDocument]$Document)
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Indent = $true
    $settings.OmitXmlDeclaration = $true
    $builder = New-Object System.Text.StringBuilder
    $writer = [System.Xml.XmlWriter]::Create($builder, $settings)
    try {
        $Document.Save($writer)
    } finally {
        if ($null -ne $writer) { $writer.Dispose() }
    }
    return $builder.ToString()
}

$InputPath = [System.IO.Path]::GetFullPath($InputPath)
$MappingCsv = [System.IO.Path]::GetFullPath($MappingCsv)
$OmmlCandidateCsv = [System.IO.Path]::GetFullPath($OmmlCandidateCsv)
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if ([string]::IsNullOrWhiteSpace($ReportPath)) {
    $ReportPath = Join-Path (Split-Path -Parent $OutputPath) 'formula-ole-apply-report.csv'
}
$ReportPath = [System.IO.Path]::GetFullPath($ReportPath)

foreach ($path in @($InputPath, $MappingCsv, $OmmlCandidateCsv)) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Required input not found: $path" }
}
$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
if ([string]::Equals($InputPath, $OutputPath, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "OutputPath must differ from InputPath; the source PPTX is never modified in place."
}

$whitelist = Get-PhysicsPptFormulaWhitelist
$whitelistNames = @{}
foreach ($rule in $whitelist) { $whitelistNames[[string]$rule.name] = $true }

$candidateRows = @(Import-Csv -LiteralPath $OmmlCandidateCsv -Encoding UTF8 | Where-Object { $_.Status -eq 'Generated' })
$candidateByName = @{}
foreach ($candidate in $candidateRows) {
    if (-not $candidateByName.ContainsKey([string]$candidate.Name)) {
        $candidateByName[[string]$candidate.Name] = $candidate
    }
}

$mappingRows = @(Import-Csv -LiteralPath $MappingCsv -Encoding UTF8 | Select-Object -First $MaxItems)

$reportRows = New-Object System.Collections.Generic.List[object]
$inputFileName = [System.IO.Path]::GetFileName($InputPath)
Copy-Item -LiteralPath $InputPath -Destination $OutputPath -Force

$docsByPart = @{}
$nssByPart = @{}
$zip = $null
try {
    $zip = [System.IO.Compression.ZipFile]::Open($OutputPath, [System.IO.Compression.ZipArchiveMode]::Update)
    $inventory = Get-OleInventory -Zip $zip -DocsByPart $docsByPart -NssByPart $nssByPart
    $byIndex = @{}
    foreach ($item in $inventory) { $byIndex[[int]$item.Index] = $item }
    $dirtyParts = @{}
    $usedIndexes = @{}

    foreach ($row in $mappingRows) {
        $slideNo = 0
        $null = [int]::TryParse([string]$row.Slide, [ref]$slideNo)
        $name = [string]$row.WhitelistName
        $rowLabel = 'slide {0}; indexes {1}; {2}' -f $slideNo, [string]$row.OleIndex, $name

        if (-not $whitelistNames.ContainsKey($name)) {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleWhitelistRejected' -Details ("whitelist name not in current config: {0}" -f $rowLabel)
            continue
        }
        if (-not $candidateByName.ContainsKey($name)) {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleCandidateMissing' -Details ("no Generated candidate: {0}" -f $rowLabel)
            continue
        }
        $candidate = $candidateByName[$name]
        if ([string]$candidate.TargetSource -ne 'CurrentConfig') {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleWhitelistRejected' -Details ("candidate TargetSource='{0}'; only CurrentConfig candidates may be applied." -f $candidate.TargetSource)
            continue
        }
        $fragmentPath = [string]$candidate.OmmlFragment
        if ([string]::IsNullOrWhiteSpace($fragmentPath) -or -not (Test-Path -LiteralPath $fragmentPath)) {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleFragmentMissing' -Details $fragmentPath
            continue
        }

        $targets = @()
        $ok = $true
        foreach ($piece in @([string]$row.OleIndex -split ';')) {
            $idx = 0
            if (-not [int]::TryParse($piece.Trim(), [ref]$idx)) {
                Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleMappingInvalidIndex' -Details ("'{0}' in {1}" -f $piece, $rowLabel)
                $ok = $false
                break
            }
            if ($usedIndexes.ContainsKey($idx)) {
                Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleIndexReused' -Details ("index {0} already targeted ({1})" -f $idx, $rowLabel)
                $ok = $false
                break
            }
            if (-not $byIndex.ContainsKey($idx)) {
                Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleIndexOutOfRange' -Details ("index {0} not in inventory ({1})" -f $idx, $rowLabel)
                $ok = $false
                break
            }
            $item = $byIndex[$idx]
            if ($item.ProgId -notlike 'Equation*') {
                Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleNotEquationObject' -Details ("index {0} progId='{1}' ({2})" -f $idx, $item.ProgId, $rowLabel)
                $ok = $false
                break
            }
            $null = $usedIndexes.Add($idx, $true)
            $targets += $item
        }
        if (-not $ok) { continue }
        if (@($targets | Where-Object { [int]$_.Slide -ne $slideNo }).Count -gt 0) {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleSlideMismatch' -Details $rowLabel
            continue
        }

        $sizePt = 0
        if (-not [int]::TryParse([string]$row.SizePt, [ref]$sizePt) -or $sizePt -lt 8 -or $sizePt -gt 96) {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleMappingInvalidSize' -Details ("SizePt='{0}' ({1})" -f [string]$row.SizePt, $rowLabel)
            continue
        }
        $mainHex = ([string]$row.MainColorHex).TrimStart('#').ToUpperInvariant()
        $subHex = ([string]$row.SubColorHex).TrimStart('#').ToUpperInvariant()
        if ($mainHex -notmatch '^[0-9A-F]{6}$') {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleMappingInvalidColor' -Details ("MainColorHex='{0}' ({1})" -f $mainHex, $rowLabel)
            continue
        }
        if (-not [string]::IsNullOrWhiteSpace($subHex) -and $subHex -notmatch '^[0-9A-F]{6}$') {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleMappingInvalidColor' -Details ("SubColorHex='{0}' ({1})" -f $subHex, $rowLabel)
            continue
        }
        $accentHex = ''
        if ($null -ne $row.PSObject.Properties['AccentColorHex']) { $accentHex = [string]$row.AccentColorHex }
        $accentHex = $accentHex.TrimStart('#').ToUpperInvariant()
        $accentTokens = if ($null -ne $row.PSObject.Properties['AccentTokens']) { [string]$row.AccentTokens } else { '' }
        if (-not [string]::IsNullOrWhiteSpace($accentHex) -and $accentHex -notmatch '^[0-9A-F]{6}$') {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleMappingInvalidColor' -Details ("AccentColorHex='{0}' ({1})" -f $accentHex, $rowLabel)
            continue
        }
        if (-not [string]::IsNullOrWhiteSpace($accentTokens) -and [string]::IsNullOrWhiteSpace($accentHex)) {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleMappingInvalidColor' -Details ("AccentTokens requires AccentColorHex ({0})" -f $rowLabel)
            continue
        }

        $part = [string]$targets[0].Part
        $doc = $docsByPart[$part]
        $ns = $nssByPart[$part]

        try {
            $fragmentDoc = Convert-OmmlFragmentDocument -FragmentPath $fragmentPath -SizePt $sizePt -MainHex $mainHex -SubHex $subHex -FontName $MathFontName -EastAsianFontName $EastAsianFontName -AccentHex $accentHex -AccentTokens $accentTokens
            # Timing safety: the slide's animation tree references shape spids.
            # Reusing the replaced block's own cNvPr id keeps those references
            # valid (the formula inherits the OLE's animation slot). Multi-target
            # rows would strand the extra ids, so they are refused here.
            $timingSpids = @()
            foreach ($spidNode in @($doc.SelectNodes('//p:timing//p:spTgt', $ns))) {
                $timingSpids += [string]$spidNode.GetAttribute('spid')
            }
            if (@($targets).Count -gt 1) {
                $extraIds = @()
                for ($t = 1; $t -lt @($targets).Count; $t++) {
                    $ownIdNode = $targets[$t].Node.SelectSingleNode('./p:nvGraphicFramePr/p:cNvPr', $ns)
                    if ($null -ne $ownIdNode) { $extraIds += [string]$ownIdNode.GetAttribute('id') }
                }
                if (@($extraIds | Where-Object { $timingSpids -contains $_ }).Count -gt 0) {
                    Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleTimingDangling' -Details ("merged targets carry animated spids ({0}); conversion skipped: {1}" -f ($extraIds -join ','), $rowLabel)
                    continue
                }
            }
            $reuseId = 0
            $ownIdNode = $targets[0].Node.SelectSingleNode('./p:nvGraphicFramePr/p:cNvPr', $ns)
            if ($null -ne $ownIdNode) { $null = [int]::TryParse([string]$ownIdNode.GetAttribute('id'), [ref]$reuseId) }
            $maxId = 0
            foreach ($idNode in @($doc.SelectNodes('//*[@id]', $ns))) {
                $candidateId = 0
                if ([int]::TryParse([string]$idNode.GetAttribute('id'), [ref]$candidateId) -and $candidateId -gt $maxId) { $maxId = $candidateId }
            }
            $finalId = if ($reuseId -gt 0 -and $reuseId -le $maxId) { $reuseId } else { $maxId + 1 }
            $shapeName = 'FormulaOmml {0}' -f $name
            $null = New-OleReplacementAlternateContent -SlideDocument $doc -NamespaceManager $ns -Targets $targets -FragmentDoc $fragmentDoc -ShapeName $shapeName -NewId $finalId
            $dirtyParts[$part] = $true
            $indexLabel = (($targets | ForEach-Object { [string]$_.Index }) -join ';')
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $shapeName -Issue 'OleFormulaReplaced' -Details ("indexes={0}; shapeId={1}; targetUnicodeMath={2}; sizePt={3}; color={4}/{5}; progId={6}" -f $indexLabel, $finalId, $candidate.TargetUnicodeMath, $sizePt, $mainHex, $subHex, [string]$targets[0].ProgId)
        } catch {
            Add-ReportRow -Rows $reportRows -File $inputFileName -Slide $slideNo -Shape $name -Issue 'OleReplaceFailed' -Details ("{0}: {1}" -f $rowLabel, $_.Exception.Message)
        }
    }

    foreach ($part in ($dirtyParts.Keys | Sort-Object)) {
        Write-ZipEntryText -Zip $zip -EntryName $part -Text (Convert-XmlDocumentToString -Document $docsByPart[$part])
    }
} finally {
    if ($null -ne $zip) { $zip.Dispose() }
}

Add-ReportRow -Rows $reportRows -File $inputFileName -Slide 0 -Shape '(presentation)' -Issue 'SavedAs' -Details $OutputPath
Write-Report -Rows $reportRows -Path $ReportPath
Write-Host "Report saved: $ReportPath"
