<#
.SYNOPSIS
  Apply reviewed formula whitelist candidates as SVG overlays in a copied PPTX.

.DESCRIPTION
  Reads formula-review.csv, renders rows with SuggestedAction=ReviewWhitelistConversion
  to SVG through Render-FormulaSvg.mjs, inserts the SVG at the matched shape bounds,
  hides the original text shape, and saves a new PPTX. The source PPTX is never modified.

.PARAMETER InputPath
  Source .pptx/.pptm file.

.PARAMETER FormulaReviewCsv
  formula-review.csv generated by Invoke-PhysicsPptWorkflow.ps1.

.PARAMETER OutputPath
  New PPTX path to save.

.PARAMETER SvgOutputDir
  Directory for generated SVG files. Defaults next to OutputPath.

.PARAMETER ReportPath
  CSV report path. Defaults next to OutputPath.

.PARAMETER MaxItems
  Maximum whitelist rows to apply in one run. Defaults to 10.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$FormulaReviewCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [string]$ReviewFileName,

    [string]$SvgOutputDir,

    [string]$ReportPath,

    [string]$NodeExe = 'node',

    [ValidateRange(1, 100)]
    [int]$MaxItems = 10
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'PhysicsPpt.Common.ps1')

$script:MsoTrue = -1
$script:MsoFalse = 0
$script:MsoGroup = 6

# Apply-time whitelist re-validation: the scan-time match is never trusted on
# its own, so a stale or hand-edited review CSV cannot smuggle in a formula
# that the current config whitelist does not cover.
$script:FormulaWhitelist = Get-PhysicsPptFormulaWhitelist
if ($script:FormulaWhitelist.Count -eq 0) {
    Write-Warning "Formula whitelist is empty or unavailable; every candidate row will be rejected."
}

function Get-ShapeText {
    param($Shape)
    try {
        if ($null -ne $Shape.TextFrame2 -and $Shape.TextFrame2.HasText -eq $script:MsoTrue) {
            return [string]$Shape.TextFrame2.TextRange.Text
        }
    } catch { }
    return ''
}

function Find-MatchingShape {
    # Priority: name+text pair, then a unique formula-text match (default shape
    # names are re-localized by PowerPoint on every save, so the scan-time name
    # may not survive normalization). Ambiguous matches return $null and are
    # reported instead of guessed.
    param($Slide, [string]$ShapeName, [string]$FormulaText)
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    $nameMatches = New-Object System.Collections.Generic.List[object]
    $textMatches = New-Object System.Collections.Generic.List[object]

    foreach ($shape in $Slide.Shapes) {
        try {
            $shapeNorm = Get-NormalizedFormulaText -Text (Get-ShapeText -Shape $shape)
            $textHit = (-not [string]::IsNullOrWhiteSpace($formulaNorm) -and $shapeNorm.Contains($formulaNorm))
            $nameHit = ([string]$shape.Name -eq $ShapeName)
            if ($textHit -and $nameHit) { return $shape }
            if ($textHit) { $textMatches.Add($shape) | Out-Null }
            elseif ($nameHit) { $nameMatches.Add($shape) | Out-Null }
        } catch { }
    }

    if ($textMatches.Count -eq 1) { return $textMatches[0] }
    return $null
}

function Get-MatchingShapeAmbiguity {
    param($Slide, [string]$ShapeName, [string]$FormulaText)
    $formulaNorm = Get-NormalizedFormulaText -Text $FormulaText
    $textHitCount = 0
    $nameHitCount = 0
    foreach ($shape in $Slide.Shapes) {
        try {
            $shapeNorm = Get-NormalizedFormulaText -Text (Get-ShapeText -Shape $shape)
            $textHit = (-not [string]::IsNullOrWhiteSpace($formulaNorm) -and $shapeNorm.Contains($formulaNorm))
            $nameHit = ([string]$shape.Name -eq $ShapeName)
            if ($textHit -and $nameHit) { return 1 }
            if ($textHit) { $textHitCount++ }
            elseif ($nameHit) { $nameHitCount++ }
        } catch { }
    }
    if ($textHitCount -gt 0) { return $textHitCount }
    return $nameHitCount
}

function Add-ReportRow {
    param(
        [System.Collections.Generic.List[object]]$Rows,
        [string]$File,
        [int]$Slide,
        [string]$Shape,
        [string]$Issue,
        [string]$Details
    )

    $Rows.Add([pscustomobject]@{
        Timestamp = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        File = $File
        Slide = $Slide
        Shape = $Shape
        Issue = $Issue
        Details = $Details
    }) | Out-Null
}

function Write-Report {
    param([System.Collections.Generic.List[object]]$Rows, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = $Rows | ConvertTo-Csv -NoTypeInformation
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

$InputPath = [System.IO.Path]::GetFullPath($InputPath)
$FormulaReviewCsv = [System.IO.Path]::GetFullPath($FormulaReviewCsv)
$OutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if ([string]::IsNullOrWhiteSpace($SvgOutputDir)) {
    $SvgOutputDir = Join-Path (Split-Path -Parent $OutputPath) 'formula-svg'
}
$SvgOutputDir = [System.IO.Path]::GetFullPath($SvgOutputDir)
if ([string]::IsNullOrWhiteSpace($ReportPath)) {
    $ReportPath = Join-Path (Split-Path -Parent $OutputPath) 'formula-svg-apply-report.csv'
}
$ReportPath = [System.IO.Path]::GetFullPath($ReportPath)

if (-not (Test-Path -LiteralPath $InputPath)) { throw "InputPath not found: $InputPath" }
if (-not (Test-Path -LiteralPath $FormulaReviewCsv)) { throw "FormulaReviewCsv not found: $FormulaReviewCsv" }
if (-not (Test-Path -LiteralPath $SvgOutputDir)) { New-Item -ItemType Directory -Path $SvgOutputDir -Force | Out-Null }
$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
if ([string]::Equals($InputPath, $OutputPath, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "OutputPath must differ from InputPath; the source PPTX is never modified in place."
}
$reportDir = Split-Path -Parent $ReportPath
if (-not (Test-Path -LiteralPath $reportDir)) { New-Item -ItemType Directory -Path $reportDir -Force | Out-Null }

$renderer = Join-Path $PSScriptRoot 'Render-FormulaSvg.mjs'
if (-not (Test-Path -LiteralPath $renderer)) { throw "Renderer not found: $renderer" }

$rows = New-Object System.Collections.Generic.List[object]
$inputFileName = [System.IO.Path]::GetFileName($InputPath)
$reviewFileNameForMatch = if ([string]::IsNullOrWhiteSpace($ReviewFileName)) { $inputFileName } else { [string]$ReviewFileName }
# File filter mirrors Apply-FormulaOmmlWhitelist: a batch-aggregated review CSV
# must never apply another deck's rows to this deck.
$reviewRows = @(
    Import-Csv -LiteralPath $FormulaReviewCsv -Encoding UTF8 |
        Where-Object {
            $_.SuggestedAction -eq 'ReviewWhitelistConversion' -and (
                ($null -ne $_.PSObject.Properties['FilePath'] -and $_.FilePath -eq $reviewFileNameForMatch) -or
                $_.File -eq $reviewFileNameForMatch
            )
        } |
        Select-Object -First $MaxItems
)

if ($reviewRows.Count -eq 0) {
    Add-ReportRow -Rows $rows -File $inputFileName -Slide 0 -Shape '(presentation)' -Issue 'NoFormulaWhitelistCandidate' -Details 'No matching ReviewWhitelistConversion rows found.'
    Write-Report -Rows $rows -Path $ReportPath
    Write-Host "Report saved: $ReportPath"
    return
}

Copy-Item -LiteralPath $InputPath -Destination $OutputPath -Force

$pp = $null
$pres = $null
try {
    $pp = New-PowerPointApplication
    $pres = Invoke-WithComRetry -Action { $pp.Presentations.Open($OutputPath, $script:MsoFalse, $script:MsoFalse, $script:MsoFalse) }

    foreach ($row in $reviewRows) {
        if ([string]$row.Slide -notmatch '^\d+$') {
            Add-ReportRow -Rows $rows -File $row.File -Slide 0 -Shape ([string]$row.Shape) -Issue 'FormulaRowInvalidSlide' -Details ("Slide='{0}'" -f $row.Slide)
            continue
        }
        $slideNo = [int]$row.Slide
        $shapeName = [string]$row.Shape

        # Apply-time whitelist re-validation against the current config; both
        # the source text and the TeX target must still match (case-sensitive).
        $rule = Test-FormulaWhitelistMatch -Text ([string]$row.FormulaText) -Whitelist $script:FormulaWhitelist
        if ($null -eq $rule) {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaWhitelistRejected' -Details ("No case-sensitive whitelist match in current config for: {0}" -f $row.FormulaText)
            continue
        }
        $ruleTex = Get-FormulaRuleValue -Rule $rule -Name 'targetTex'
        $tex = Get-FormulaDetailValue -Details ([string]$row.WhitelistCandidate) -Key 'targetTex'
        if ([string]::IsNullOrWhiteSpace($tex)) {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgSkipped' -Details 'WhitelistCandidate does not contain targetTex.'
            continue
        }
        if (-not [string]::Equals($tex, $ruleTex, [System.StringComparison]::Ordinal)) {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaWhitelistRejected' -Details ("candidate targetTex '{0}' does not match current whitelist '{1}'." -f $tex, $ruleTex)
            continue
        }

        # Pass TeX through a UTF-8 file: command-line quoting rules differ between
        # hosts and can corrupt formulas containing quotes or trailing backslashes.
        $svgName = 'slide-{0:000}-{1}' -f $slideNo, (Convert-ToSafeFormulaPathSegment -Name $shapeName)
        $svgPath = Join-Path $SvgOutputDir ($svgName + '.svg')
        $texPath = Join-Path $SvgOutputDir ($svgName + '.tex')
        [System.IO.File]::WriteAllText($texPath, $tex, (New-Object System.Text.UTF8Encoding($false)))
        $renderArgs = @($renderer, '--tex-file', $texPath, '--out', $svgPath)
        $renderOutput = $null
        $previousEap = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        try {
            $renderOutput = & $NodeExe @renderArgs 2>&1
        } finally {
            $ErrorActionPreference = $previousEap
        }
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $svgPath)) {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgRenderFailed' -Details (($renderOutput | Out-String).Trim())
            continue
        }

        $slide = $null
        $shape = $null
        $inserted = $null
        try {
            $slide = $pres.Slides.Item($slideNo)
            $shape = Find-MatchingShape -Slide $slide -ShapeName $shapeName -FormulaText ([string]$row.FormulaText)
            if ($null -eq $shape) {
                $matchCount = Get-MatchingShapeAmbiguity -Slide $slide -ShapeName $shapeName -FormulaText ([string]$row.FormulaText)
                $reason = if ($matchCount -gt 1) { "found on {0} shapes; ambiguous." -f $matchCount } else { 'no shape with this name carries the formula text.' }
                Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaShapeNotFound' -Details $reason
                continue
            }
            $shapeType = 0
            try { $shapeType = [int]$shape.Type } catch { }
            if ($shapeType -eq $script:MsoGroup) {
                Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgSkipped' -Details 'Group shapes are skipped by default.'
                continue
            }

            $left = [single]$shape.Left
            $top = [single]$shape.Top
            $width = [single]$shape.Width
            $height = [single]$shape.Height
            $inserted = $slide.Shapes.AddPicture($svgPath, $script:MsoFalse, $script:MsoTrue, $left, $top, $width, $height)
            $inserted.Name = 'FormulaSvg_' + (Convert-ToSafeFormulaPathSegment -Name $shapeName)
            $shape.Visible = $script:MsoFalse
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgInserted' -Details ("tex={0}; svg={1}; original hidden." -f $tex, $svgPath)
        } catch {
            Add-ReportRow -Rows $rows -File $row.File -Slide $slideNo -Shape $shapeName -Issue 'FormulaSvgInsertFailed' -Details $_.Exception.Message
        } finally {
            Release-ComObjectSafe -ComObject $inserted
            Release-ComObjectSafe -ComObject $shape
            Release-ComObjectSafe -ComObject $slide
        }
    }

    Invoke-WithComRetry -Action { $pres.SaveAs($OutputPath) } | Out-Null
    Add-ReportRow -Rows $rows -File $inputFileName -Slide 0 -Shape '(presentation)' -Issue 'SavedAs' -Details $OutputPath
} finally {
    if ($null -ne $pres) {
        try { $pres.Close() | Out-Null } catch { }
        Release-ComObjectSafe -ComObject $pres
    }
    if ($null -ne $pp) {
        try { $pp.Quit() | Out-Null } catch { }
        Release-ComObjectSafe -ComObject $pp
    }
    [System.GC]::Collect()
    [System.GC]::WaitForPendingFinalizers()
}

Write-Report -Rows $rows -Path $ReportPath
Write-Host "Report saved: $ReportPath"
Write-Host "Output saved: $OutputPath"
