<#
.SYNOPSIS
  Build a review list of image assets that may contain formulas.

.DESCRIPTION
  Reads pptx-image-candidates.csv generated by Export-PptxImageCandidates.ps1
  and scores diagram/text-like images for formula likelihood so the carrier
  inventory can tell image-borne formulas from OLE/OfficeMath carriers.
  This tool does not modify PPTX files.

.PARAMETER ImageCandidateCsv
  pptx-image-candidates.csv from Export-PptxImageCandidates.ps1.

.PARAMETER OutputDir
  Directory where reports are written.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ImageCandidateCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputDir,

    [ValidateRange(1, 100)]
    [int]$MinScore = 45
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'PhysicsPpt.Common.ps1')

# Convert-ToSafePathSegment comes from PhysicsPpt.Common.ps1; the shared version
# preserves dots (deliverable convention, e.g. "13.2内能") instead of collapsing them.

function Convert-ToDoubleLenient {
    param([object]$Value)
    $text = [string]$Value
    if ([string]::IsNullOrWhiteSpace($text)) { return 0.0 }
    $parsed = 0.0
    if ([double]::TryParse($text, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
        return $parsed
    }
    if ([double]::TryParse($text, [ref]$parsed)) { return $parsed }
    return 0.0
}

function Convert-ToInt64 {
    param([object]$Value)
    $text = [string]$Value
    if ([string]::IsNullOrWhiteSpace($text)) { return [int64]0 }
    $parsed = [int64]0
    if ([int64]::TryParse($text, [ref]$parsed)) { return $parsed }
    return [int64]0
}

function Get-FormulaImageAssessment {
    param([object]$Row)

    $score = 0
    $reasons = New-Object System.Collections.Generic.List[string]
    $edgeDensity = Convert-ToDoubleLenient (Get-RowValue -Row $Row -Name 'EdgeDensity')
    $colorDiversity = Convert-ToDoubleLenient (Get-RowValue -Row $Row -Name 'ColorDiversity')
    $grayRatio = Convert-ToDoubleLenient (Get-RowValue -Row $Row -Name 'GrayRatio')
    $transparentRatio = Convert-ToDoubleLenient (Get-RowValue -Row $Row -Name 'TransparentRatio')
    $uniqueColorBins = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'UniqueColorBins')
    $pixels = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'Pixels')
    $width = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'Width')
    $height = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'Height')
    $candidateLevel = [string](Get-RowValue -Row $Row -Name 'CandidateLevel')
    $mediaRole = [string](Get-RowValue -Row $Row -Name 'MediaRole' -Default 'StandaloneImage')

    if ($mediaRole -ne 'StandaloneImage') {
        return [pscustomobject]@{
            FormulaImageScore = 0
            FormulaImageCandidate = $false
            FormulaCandidateLevel = 'Excluded'
            FormulaCandidateReason = 'Not a standalone image'
        }
    }

    if ($candidateLevel -eq 'LikelyDiagramOrText') {
        $score += 25
        $reasons.Add('diagram/text classifier') | Out-Null
    } elseif ($candidateLevel -eq 'TooSmall') {
        $score -= 10
        $reasons.Add('small image') | Out-Null
    }

    if ($edgeDensity -ge 0.18) {
        $score += 30
        $reasons.Add('high edge density') | Out-Null
    } elseif ($edgeDensity -ge 0.10) {
        $score += 18
        $reasons.Add('moderate edge density') | Out-Null
    } elseif ($edgeDensity -lt 0.03) {
        $score -= 10
        $reasons.Add('low edge density') | Out-Null
    }

    if ($colorDiversity -le 0.08) {
        $score += 15
        $reasons.Add('low color diversity') | Out-Null
    } elseif ($colorDiversity -ge 0.18) {
        $score -= 10
        $reasons.Add('photo-like color diversity') | Out-Null
    }

    if ($grayRatio -ge 0.65) {
        $score += 12
        $reasons.Add('mostly grayscale') | Out-Null
    }

    if ($uniqueColorBins -le 220 -and $uniqueColorBins -gt 0) {
        $score += 8
        $reasons.Add('limited color bins') | Out-Null
    }

    if ($transparentRatio -gt 0.02) {
        $score += 6
        $reasons.Add('transparent overlay asset') | Out-Null
    }

    if ($pixels -ge 5000 -and $pixels -le 2500000) {
        $score += 5
    }

    if ($width -gt 0 -and $height -gt 0) {
        $ratio = [Math]::Max($width, $height) / [double][Math]::Max(1, [Math]::Min($width, $height))
        if ($ratio -ge 2.5) {
            $score += 5
            $reasons.Add('wide or tall formula-like aspect') | Out-Null
        }
    }

    $boundedScore = [Math]::Max(0, [Math]::Min(100, $score))
    $isCandidate = $boundedScore -ge $MinScore
    $level = if ($boundedScore -ge 70) {
        'LikelyFormulaImage'
    } elseif ($isCandidate) {
        'MaybeFormulaImage'
    } else {
        'UnlikelyFormulaImage'
    }

    if ($reasons.Count -eq 0) { $reasons.Add('No formula-like visual signals') | Out-Null }
    return [pscustomobject]@{
        FormulaImageScore = $boundedScore
        FormulaImageCandidate = $isCandidate
        FormulaCandidateLevel = $level
        FormulaCandidateReason = ($reasons -join '; ')
    }
}

$ImageCandidateCsv = [System.IO.Path]::GetFullPath($ImageCandidateCsv)
$OutputDir = [System.IO.Path]::GetFullPath($OutputDir)
if (-not (Test-Path -LiteralPath $ImageCandidateCsv)) { throw "ImageCandidateCsv not found: $ImageCandidateCsv" }
if (-not (Test-Path -LiteralPath $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$sourceRows = @(Import-Csv -LiteralPath $ImageCandidateCsv -Encoding UTF8)
$rows = New-Object System.Collections.Generic.List[object]
foreach ($row in $sourceRows) {
    $assessment = Get-FormulaImageAssessment -Row $row

    $rows.Add([pscustomobject]@{
        Deck = Get-RowValue -Row $row -Name 'Deck'
        DeckPath = Get-RowValue -Row $row -Name 'DeckPath'
        MediaPath = Get-RowValue -Row $row -Name 'MediaPath'
        Extension = Get-RowValue -Row $row -Name 'Extension'
        MediaRole = Get-RowValue -Row $row -Name 'MediaRole' -Default 'StandaloneImage'
        UsedOnSlides = Get-RowValue -Row $row -Name 'UsedOnSlides'
        OriginalBytes = Get-RowValue -Row $row -Name 'OriginalBytes'
        Width = Get-RowValue -Row $row -Name 'Width'
        Height = Get-RowValue -Row $row -Name 'Height'
        Pixels = Get-RowValue -Row $row -Name 'Pixels'
        ColorDiversity = Get-RowValue -Row $row -Name 'ColorDiversity'
        GrayRatio = Get-RowValue -Row $row -Name 'GrayRatio'
        TransparentRatio = Get-RowValue -Row $row -Name 'TransparentRatio'
        EdgeDensity = Get-RowValue -Row $row -Name 'EdgeDensity'
        SourceCandidateLevel = Get-RowValue -Row $row -Name 'CandidateLevel'
        FormulaImageScore = $assessment.FormulaImageScore
        FormulaImageCandidate = $assessment.FormulaImageCandidate
        FormulaCandidateLevel = $assessment.FormulaCandidateLevel
        FormulaCandidateReason = $assessment.FormulaCandidateReason
        SuggestedAction = if ($assessment.FormulaImageCandidate) { 'ReviewImageFormula' } else { 'IgnoreForFormula' }
    }) | Out-Null
}

$csvPath = Join-Path $OutputDir 'formula-image-candidates.csv'
$jsonPath = Join-Path $OutputDir 'formula-image-candidates.json'
$manifestPath = Join-Path $OutputDir 'formula-image-candidates-manifest.json'

$sorted = @($rows | Sort-Object @{ Expression = 'FormulaImageCandidate'; Descending = $true }, @{ Expression = 'FormulaImageScore'; Descending = $true }, Deck, MediaPath)
Write-Utf8BomCsv -InputObject $sorted -Path $csvPath
$sorted | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$candidateRows = @($rows | Where-Object { $_.FormulaImageCandidate })
$manifest = [pscustomobject]@{
    generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    imageCandidateCsv = $ImageCandidateCsv
    outputDir = $OutputDir
    rowCount = $rows.Count
    formulaImageCandidateCount = $candidateRows.Count
    minScore = $MinScore
    csv = $csvPath
    json = $jsonPath
    note = 'Read-only formula image candidate scan feeding the carrier inventory.'
}
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Write-Host "Formula image candidate scan done: $OutputDir"
Write-Host "Candidates: $($candidateRows.Count) / Images: $($rows.Count)"
