<#
.SYNOPSIS
  Build an automatic visual confirmation gate from rendered PPTX audit artifacts.

.DESCRIPTION
  Reads the artifacts generated by Export-PptxVisualAudit.ps1 and produces a
  slide-level confirmation CSV, a JSON manifest, and an optional contact sheet.
  When a baseline audit directory is supplied, known source issues are allowed
  while newly introduced errors fail the gate. The script never modifies PPTX.

.PARAMETER VisualAuditDir
  Directory containing pptx-visual-audit.csv and pptx-slide-visual-metrics.csv.

.PARAMETER BaselineVisualAuditDir
  Optional prior audit directory used to distinguish known issues from new ones.

.PARAMETER OutputDir
  Directory for visual confirmation outputs. Defaults to VisualAuditDir.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$VisualAuditDir,

    [string]$BaselineVisualAuditDir,

    [string]$OutputDir,

    [ValidateRange(0.1, 100)]
    [double]$MaxAllowedVisualDeltaPercent = 8.0,

    [ValidateRange(0.1, 100)]
    [double]$MaxAllowedMetricDeltaPercent = 8.0,

    [ValidateRange(1, 200)]
    [int]$MaxContactSheetItems = 80,

    [switch]$ContactSheet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Utf8BomCsv {
    param([object[]]$Rows, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    $csvLines = $Rows | ConvertTo-Csv -NoTypeInformation
    [System.IO.File]::WriteAllLines($Path, $csvLines, $utf8Bom)
}

function Write-Utf8BomText {
    param([string]$Text, [string]$Path)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Path, $Text, $utf8Bom)
}

function Import-CsvIfExists {
    param([string]$Path)
    if ([string]::IsNullOrWhiteSpace($Path) -or -not (Test-Path -LiteralPath $Path)) { return @() }
    return @(Import-Csv -LiteralPath $Path -Encoding UTF8)
}

function Get-AuditIssueKey {
    param($Row)
    return ('{0}|{1}|{2}|{3}' -f [string]$Row.Slide, [string]$Row.Shape, [string]$Row.Issue, [string]$Row.Severity)
}

function Get-AuditIssueFallbackKey {
    param($Row)
    return ('{0}|{1}|{2}' -f [string]$Row.Slide, [string]$Row.Issue, [string]$Row.Severity)
}

function Add-MapCount {
    param([hashtable]$Map, [string]$Key)
    if ([string]::IsNullOrWhiteSpace($Key)) { return }
    if (-not $Map.ContainsKey($Key)) { $Map[$Key] = 0 }
    $Map[$Key] = [int]$Map[$Key] + 1
}

function Get-AuditIssueMaps {
    param($Rows)

    $exact = @{}
    $fallback = @{}
    foreach ($row in @($Rows)) {
        if ($null -eq $row) { continue }
        if ($row.PSObject.Properties.Name -notcontains 'Slide' -or $row.PSObject.Properties.Name -notcontains 'Severity') { continue }
        if ($row.Slide -notmatch '^\d+$' -or [int]$row.Slide -le 0 -or $row.Severity -notin @('Error', 'Warning')) { continue }
        Add-MapCount -Map $exact -Key (Get-AuditIssueKey -Row $row)
        Add-MapCount -Map $fallback -Key (Get-AuditIssueFallbackKey -Row $row)
    }
    return [pscustomobject]@{
        Exact = $exact
        Fallback = $fallback
    }
}

function Test-BaselineIssueKnown {
    param($Row, $IssueMaps)

    if ($null -eq $IssueMaps) { return $false }
    $exactKey = Get-AuditIssueKey -Row $Row
    if ($IssueMaps.Exact.ContainsKey($exactKey)) { return $true }

    $fallbackKey = Get-AuditIssueFallbackKey -Row $Row
    if ($IssueMaps.Fallback.ContainsKey($fallbackKey)) { return $true }
    return $false
}

function Get-ImageDeltaPercent {
    param(
        [string]$BeforePath,
        [string]$AfterPath
    )

    if ([string]::IsNullOrWhiteSpace($BeforePath) -or [string]::IsNullOrWhiteSpace($AfterPath)) { return $null }
    if (-not (Test-Path -LiteralPath $BeforePath) -or -not (Test-Path -LiteralPath $AfterPath)) { return $null }

    Add-Type -AssemblyName System.Drawing
    $before = $null
    $after = $null
    $beforeThumb = $null
    $afterThumb = $null
    try {
        $before = [System.Drawing.Image]::FromFile($BeforePath)
        $after = [System.Drawing.Image]::FromFile($AfterPath)
        $width = 160
        $height = 90
        $beforeThumb = New-Object System.Drawing.Bitmap $before, $width, $height
        $afterThumb = New-Object System.Drawing.Bitmap $after, $width, $height
        [double]$sum = 0
        for ($y = 0; $y -lt $height; $y++) {
            for ($x = 0; $x -lt $width; $x++) {
                $a = $beforeThumb.GetPixel($x, $y)
                $b = $afterThumb.GetPixel($x, $y)
                $sum += ([Math]::Abs($a.R - $b.R) + [Math]::Abs($a.G - $b.G) + [Math]::Abs($a.B - $b.B)) / (3 * 255)
            }
        }
        return [Math]::Round(($sum / ($width * $height)) * 100, 2)
    } catch {
        return $null
    } finally {
        if ($null -ne $afterThumb) { $afterThumb.Dispose() }
        if ($null -ne $beforeThumb) { $beforeThumb.Dispose() }
        if ($null -ne $after) { $after.Dispose() }
        if ($null -ne $before) { $before.Dispose() }
    }
}

function Convert-ToStatusColor {
    param([string]$Status)
    switch ($Status) {
        'Passed' { return [System.Drawing.Color]::FromArgb(38, 132, 78) }
        'PassedWithKnownIssues' { return [System.Drawing.Color]::FromArgb(42, 117, 181) }
        'NeedsReview' { return [System.Drawing.Color]::FromArgb(211, 131, 18) }
        'Failed' { return [System.Drawing.Color]::FromArgb(196, 45, 45) }
        default { return [System.Drawing.Color]::FromArgb(90, 90, 90) }
    }
}

function Get-StatusRank {
    param([string]$Status)
    switch ($Status) {
        'Failed' { return 1 }
        'NeedsReview' { return 2 }
        'PassedWithKnownIssues' { return 3 }
        'Passed' { return 4 }
        default { return 9 }
    }
}

function New-VisualConfirmationContactSheet {
    param(
        [object[]]$Rows,
        [string]$OutputPath,
        [int]$MaxItems
    )

    Add-Type -AssemblyName System.Drawing
    $items = @(
        $Rows |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_.PageImage) -and (Test-Path -LiteralPath $_.PageImage) } |
            Sort-Object @{ Expression = { Get-StatusRank -Status ([string]$_.Status) }; Ascending = $true }, @{ Expression = { [int]$_.Slide }; Ascending = $true } |
            Select-Object -First $MaxItems
    )
    if ($items.Count -eq 0) { return $false }

    $tileWidth = 380
    $tileHeight = 280
    $imageHeight = 210
    [int]$columns = 4
    if ($items.Count -lt 4) { [int]$columns = [Math]::Max(1, [int]$items.Count) }
    $rowsCount = [int][Math]::Ceiling($items.Count / [double]$columns)
    [int]$sheetWidth = [int]$columns * [int]$tileWidth
    [int]$sheetHeight = [int]$rowsCount * [int]$tileHeight

    $bitmap = $null
    $graphics = $null
    $font = $null
    $smallFont = $null
    $pen = $null
    try {
        $bitmap = New-Object System.Drawing.Bitmap $sheetWidth, $sheetHeight
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.Clear([System.Drawing.Color]::White)
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $font = New-Object System.Drawing.Font('Arial', 12, [System.Drawing.FontStyle]::Bold)
        $smallFont = New-Object System.Drawing.Font('Arial', 9)

        for ($i = 0; $i -lt $items.Count; $i++) {
            $item = $items[$i]
            $x = ($i % $columns) * $tileWidth
            $y = [int][Math]::Floor($i / $columns) * $tileHeight
            $statusColor = Convert-ToStatusColor -Status ([string]$item.Status)
            $pen = New-Object System.Drawing.Pen($statusColor, 4)
            $graphics.DrawRectangle($pen, $x + 6, $y + 6, $tileWidth - 12, $tileHeight - 12)
            $pen.Dispose()
            $pen = $null

            $img = $null
            try {
                $img = [System.Drawing.Image]::FromFile([string]$item.PageImage)
                $graphics.DrawImage($img, $x + 12, $y + 12, $tileWidth - 24, $imageHeight)
            } finally {
                if ($null -ne $img) { $img.Dispose() }
            }

            $label = ('Slide {0}: {1}' -f $item.Slide, $item.Status)
            $details = [string]$item.Reason
            if ($details.Length -gt 120) { $details = $details.Substring(0, 117) + '...' }
            $brush = $null
            try {
                $brush = New-Object System.Drawing.SolidBrush($statusColor)
                $graphics.DrawString($label, $font, $brush, $x + 14, $y + $imageHeight + 20)
            } finally {
                if ($null -ne $brush) { $brush.Dispose() }
            }
            $graphics.DrawString($details, $smallFont, [System.Drawing.Brushes]::Black, $x + 14, $y + $imageHeight + 42)
        }

        $bitmap.Save($OutputPath, [System.Drawing.Imaging.ImageFormat]::Png)
        return $true
    } finally {
        if ($null -ne $pen) { $pen.Dispose() }
        if ($null -ne $smallFont) { $smallFont.Dispose() }
        if ($null -ne $font) { $font.Dispose() }
        if ($null -ne $graphics) { $graphics.Dispose() }
        if ($null -ne $bitmap) { $bitmap.Dispose() }
    }
}

$VisualAuditDir = [System.IO.Path]::GetFullPath($VisualAuditDir)
if (-not (Test-Path -LiteralPath $VisualAuditDir)) { throw "VisualAuditDir not found: $VisualAuditDir" }
if ([string]::IsNullOrWhiteSpace($OutputDir)) { $OutputDir = $VisualAuditDir }
$OutputDir = [System.IO.Path]::GetFullPath($OutputDir)
if (-not (Test-Path -LiteralPath $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$auditCsv = Join-Path $VisualAuditDir 'pptx-visual-audit.csv'
$slideMetricsCsv = Join-Path $VisualAuditDir 'pptx-slide-visual-metrics.csv'
if (-not (Test-Path -LiteralPath $auditCsv)) { throw "Visual audit CSV not found: $auditCsv" }
if (-not (Test-Path -LiteralPath $slideMetricsCsv)) { throw "Slide visual metrics CSV not found: $slideMetricsCsv" }

$baselineAuditCsv = ''
$baselineSlideMetricsCsv = ''
$hasBaseline = -not [string]::IsNullOrWhiteSpace($BaselineVisualAuditDir)
if ($hasBaseline) {
    $BaselineVisualAuditDir = [System.IO.Path]::GetFullPath($BaselineVisualAuditDir)
    if (-not (Test-Path -LiteralPath $BaselineVisualAuditDir)) { throw "BaselineVisualAuditDir not found: $BaselineVisualAuditDir" }
    $baselineAuditCsv = Join-Path $BaselineVisualAuditDir 'pptx-visual-audit.csv'
    $baselineSlideMetricsCsv = Join-Path $BaselineVisualAuditDir 'pptx-slide-visual-metrics.csv'
}

$auditRows = Import-CsvIfExists -Path $auditCsv
$slideRows = Import-CsvIfExists -Path $slideMetricsCsv
$baselineRows = Import-CsvIfExists -Path $baselineAuditCsv
$baselineSlideRows = Import-CsvIfExists -Path $baselineSlideMetricsCsv
$baselineIssueMaps = Get-AuditIssueMaps -Rows $baselineRows
$baselineSlideMap = @{}
foreach ($row in $baselineSlideRows) {
    if ($row.Slide -match '^\d+$') { $baselineSlideMap[[int]$row.Slide] = $row }
}

$slideCountMismatch = $false
if ($hasBaseline -and $baselineSlideRows.Count -gt 0 -and $baselineSlideRows.Count -ne $slideRows.Count) {
    $slideCountMismatch = $true
}

$confirmationRows = New-Object System.Collections.Generic.List[object]
foreach ($slide in @($slideRows | Sort-Object { [int]$_.Slide })) {
    $slideNo = [int]$slide.Slide
    $issues = @($auditRows | Where-Object { $_.Slide -match '^\d+$' -and [int]$_.Slide -eq $slideNo -and $_.Severity -in @('Error', 'Warning') })
    $errors = @($issues | Where-Object { $_.Severity -eq 'Error' })
    $warnings = @($issues | Where-Object { $_.Severity -eq 'Warning' })
    $newErrors = @($errors | Where-Object { -not (Test-BaselineIssueKnown -Row $_ -IssueMaps $baselineIssueMaps) })
    $newWarnings = @($warnings | Where-Object { -not (Test-BaselineIssueKnown -Row $_ -IssueMaps $baselineIssueMaps) })
    $knownIssues = @($issues | Where-Object { Test-BaselineIssueKnown -Row $_ -IssueMaps $baselineIssueMaps })
    $pageImage = [string]$slide.ImagePath

    $baselinePageImage = ''
    $deltaPercent = $null
    $whiteDelta = $null
    $nonWhiteDelta = $null
    $darkDelta = $null
    if ($baselineSlideMap.ContainsKey($slideNo)) {
        $baselinePageImage = [string]$baselineSlideMap[$slideNo].ImagePath
        $deltaPercent = Get-ImageDeltaPercent -BeforePath $baselinePageImage -AfterPath $pageImage
        try { $whiteDelta = [Math]::Round([Math]::Abs([double]$slide.WhitePercent - [double]$baselineSlideMap[$slideNo].WhitePercent), 2) } catch { $whiteDelta = $null }
        try { $nonWhiteDelta = [Math]::Round([Math]::Abs([double]$slide.NonWhitePercent - [double]$baselineSlideMap[$slideNo].NonWhitePercent), 2) } catch { $nonWhiteDelta = $null }
        try { $darkDelta = [Math]::Round([Math]::Abs([double]$slide.DarkPercent - [double]$baselineSlideMap[$slideNo].DarkPercent), 2) } catch { $darkDelta = $null }
    }

    $status = 'Passed'
    $confidence = 'High'
    $suggestedAction = 'Accept'
    $reasonParts = New-Object System.Collections.Generic.List[string]
    $newIssueNames = @(($newErrors + $newWarnings) | Select-Object -ExpandProperty Issue -Unique | Sort-Object)
    $knownIssueNames = @($knownIssues | Select-Object -ExpandProperty Issue -Unique | Sort-Object)

    if ([string]::IsNullOrWhiteSpace($pageImage) -or -not (Test-Path -LiteralPath $pageImage)) {
        $status = 'Failed'
        $confidence = 'High'
        $suggestedAction = 'FixOrRollback'
        $reasonParts.Add('Rendered page image is missing.') | Out-Null
    } elseif ($slideCountMismatch) {
        $status = 'Failed'
        $confidence = 'High'
        $suggestedAction = 'FixOrRollback'
        $reasonParts.Add("Slide count differs from baseline: current=$($slideRows.Count), baseline=$($baselineSlideRows.Count).") | Out-Null
    } elseif ($newErrors.Count -gt 0) {
        $status = 'Failed'
        $confidence = 'High'
        $suggestedAction = 'FixOrRollback'
        $reasonParts.Add(('New visual error(s): {0}' -f (($newErrors | Select-Object -ExpandProperty Issue -Unique) -join ';'))) | Out-Null
    } elseif ($errors.Count -gt 0 -and -not $hasBaseline) {
        $status = 'Failed'
        $confidence = 'High'
        $suggestedAction = 'FixOrRollback'
        $reasonParts.Add(('Visual error(s): {0}' -f (($errors | Select-Object -ExpandProperty Issue -Unique) -join ';'))) | Out-Null
    } elseif ($newWarnings.Count -gt 0) {
        $status = 'NeedsReview'
        $confidence = 'Medium'
        $suggestedAction = 'ReviewRenderedPage'
        $reasonParts.Add(('New warning(s): {0}' -f (($newWarnings | Select-Object -ExpandProperty Issue -Unique) -join ';'))) | Out-Null
    } elseif ($warnings.Count -gt 0 -and -not $hasBaseline) {
        $status = 'NeedsReview'
        $confidence = 'Medium'
        $suggestedAction = 'ReviewRenderedPage'
        $reasonParts.Add(('Warning(s): {0}' -f (($warnings | Select-Object -ExpandProperty Issue -Unique) -join ';'))) | Out-Null
    } elseif ($knownIssues.Count -gt 0) {
        $status = 'PassedWithKnownIssues'
        $confidence = 'Medium'
        $suggestedAction = 'KeepWithBaselineIssue'
        $reasonParts.Add(('Only baseline issue(s): {0}' -f ($knownIssueNames -join ';'))) | Out-Null
    }

    if ($null -ne $deltaPercent -and $deltaPercent -gt $MaxAllowedVisualDeltaPercent -and $status -notin @('Failed')) {
        $status = 'NeedsReview'
        $confidence = 'Medium'
        $suggestedAction = 'ReviewRenderedPage'
        $reasonParts.Add(("Visual delta {0}% exceeds {1}% threshold." -f $deltaPercent, $MaxAllowedVisualDeltaPercent)) | Out-Null
    }
    if (($null -ne $whiteDelta -and $whiteDelta -gt $MaxAllowedMetricDeltaPercent) -or
        ($null -ne $nonWhiteDelta -and $nonWhiteDelta -gt $MaxAllowedMetricDeltaPercent) -or
        ($null -ne $darkDelta -and $darkDelta -gt $MaxAllowedMetricDeltaPercent)) {
        if ($status -notin @('Failed')) {
            $status = 'NeedsReview'
            $confidence = 'Medium'
            $suggestedAction = 'ReviewRenderedPage'
        }
        $reasonParts.Add(("Visual metric delta exceeds {0}% threshold: white={1}; nonWhite={2}; dark={3}." -f $MaxAllowedMetricDeltaPercent, $whiteDelta, $nonWhiteDelta, $darkDelta)) | Out-Null
    }

    if ($reasonParts.Count -eq 0) { $reasonParts.Add('No blocking visual issue detected.') | Out-Null }

    $confirmationRows.Add([pscustomobject]@{
        File = [string]$slide.File
        Slide = $slideNo
        Status = $status
        Confidence = $confidence
        SuggestedAction = $suggestedAction
        ErrorCount = $errors.Count
        WarningCount = $warnings.Count
        NewErrorCount = $newErrors.Count
        NewWarningCount = $newWarnings.Count
        KnownBaselineIssueCount = $knownIssues.Count
        VisualDeltaPercent = if ($null -eq $deltaPercent) { '' } else { $deltaPercent }
        WhiteDeltaPercent = if ($null -eq $whiteDelta) { '' } else { $whiteDelta }
        NonWhiteDeltaPercent = if ($null -eq $nonWhiteDelta) { '' } else { $nonWhiteDelta }
        DarkDeltaPercent = if ($null -eq $darkDelta) { '' } else { $darkDelta }
        Reason = ($reasonParts -join ' ')
        NewIssues = ($newIssueNames -join ';')
        KnownBaselineIssues = ($knownIssueNames -join ';')
        Issues = (($issues | ForEach-Object { "$($_.Severity):$($_.Issue):$($_.Shape)" }) -join ';')
        PageImage = $pageImage
        BaselinePageImage = $baselinePageImage
    }) | Out-Null
}

$rows = @($confirmationRows.ToArray())
$failedCount = @($rows | Where-Object { $_.Status -eq 'Failed' }).Count
$needsReviewCount = @($rows | Where-Object { $_.Status -eq 'NeedsReview' }).Count
$passedWithKnownIssuesCount = @($rows | Where-Object { $_.Status -eq 'PassedWithKnownIssues' }).Count
$passedCount = @($rows | Where-Object { $_.Status -eq 'Passed' }).Count
$newErrorCount = @($rows | Measure-Object -Property NewErrorCount -Sum).Sum
if ($null -eq $newErrorCount) { $newErrorCount = 0 }
$newWarningCount = @($rows | Measure-Object -Property NewWarningCount -Sum).Sum
if ($null -eq $newWarningCount) { $newWarningCount = 0 }

$confirmationStatus = if ($failedCount -gt 0) {
    'Failed'
} elseif ($needsReviewCount -gt 0) {
    'NeedsReview'
} elseif ($passedWithKnownIssuesCount -gt 0) {
    'PassedWithKnownIssues'
} else {
    'Passed'
}

$automationGateStatus = if ($confirmationStatus -in @('Passed', 'PassedWithKnownIssues')) {
    'Passed'
} elseif ($confirmationStatus -eq 'NeedsReview') {
    'NeedsReview'
} else {
    'Failed'
}

$confirmationCsv = Join-Path $OutputDir 'pptx-visual-confirmation.csv'
$manifestPath = Join-Path $OutputDir 'pptx-visual-confirmation-manifest.json'
$contactSheetPath = Join-Path $OutputDir 'pptx-visual-confirmation.contact-sheet.png'
Write-Utf8BomCsv -Rows $rows -Path $confirmationCsv

$contactSheetCreated = $false
if ($ContactSheet) {
    $contactSheetCreated = New-VisualConfirmationContactSheet -Rows $rows -OutputPath $contactSheetPath -MaxItems $MaxContactSheetItems
}

$manifest = [ordered]@{
    generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    ruleVersion = 'visual-confirmation-v2'
    visualAuditDir = $VisualAuditDir
    baselineVisualAuditDir = if ($hasBaseline) { $BaselineVisualAuditDir } else { '' }
    outputDir = $OutputDir
    slideCount = $rows.Count
    baselineSlideCount = if ($hasBaseline) { $baselineSlideRows.Count } else { 0 }
    slideCountMismatch = $slideCountMismatch
    confirmationStatus = $confirmationStatus
    automationGateStatus = $automationGateStatus
    passedCount = $passedCount
    passedWithKnownIssuesCount = $passedWithKnownIssuesCount
    needsReviewCount = $needsReviewCount
    failedCount = $failedCount
    newErrorCount = [int]$newErrorCount
    newWarningCount = [int]$newWarningCount
    maxAllowedVisualDeltaPercent = $MaxAllowedVisualDeltaPercent
    maxAllowedMetricDeltaPercent = $MaxAllowedMetricDeltaPercent
    confirmationCsv = $confirmationCsv
    contactSheet = if ($contactSheetCreated) { $contactSheetPath } else { '' }
    rule = 'Fail missing pages, slide-count drift, or new rendered errors; keep baseline-known issues; mark new warnings, high pixel delta, or high visual metric delta for review; never modify PPTX.'
}

Write-Utf8BomText -Text ($manifest | ConvertTo-Json -Depth 6) -Path $manifestPath

Write-Host "Visual confirmation done: $OutputDir"
Write-Host "Status: $confirmationStatus; Gate: $automationGateStatus; Passed: $passedCount; Known: $passedWithKnownIssuesCount; Review: $needsReviewCount; Failed: $failedCount"
