<#
.SYNOPSIS
  Build a review list of image assets that may contain formulas.

.DESCRIPTION
  Reads pptx-image-candidates.csv generated by Export-PptxImageCandidates.ps1,
  scores diagram/text-like images for formula likelihood, optionally extracts
  matching media files from the source PPTX packages, and builds a contact
  sheet for manual review. This tool does not modify PPTX files.

.PARAMETER ImageCandidateCsv
  pptx-image-candidates.csv from Export-PptxImageCandidates.ps1.

.PARAMETER OutputDir
  Directory where reports and extracted candidate images are written.

.PARAMETER ExportCandidates
  Extract candidate media files to formula-image-candidates.

.PARAMETER ContactSheet
  Build a PNG contact sheet from exported candidates.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ImageCandidateCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputDir,

    [ValidateRange(1, 100)]
    [int]$MinScore = 45,

    [switch]$ExportCandidates,

    [switch]$ContactSheet,

    [ValidateRange(1, 500)]
    [int]$MaxContactSheetItems = 80
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Convert-ToSafePathSegment {
    param([string]$Name)
    $safe = $Name
    foreach ($ch in [System.IO.Path]::GetInvalidFileNameChars()) {
        $safe = $safe.Replace([string]$ch, '_')
    }
    $safe = $safe -replace '\s+', '_'
    $safe = $safe -replace '[^\p{L}\p{Nd}_-]+', '_'
    $safe = $safe.Trim('_')
    if ([string]::IsNullOrWhiteSpace($safe)) { return 'formula-image' }
    return $safe
}

function Convert-ToDouble {
    param([object]$Value)
    $text = [string]$Value
    if ([string]::IsNullOrWhiteSpace($text)) { return 0.0 }
    $parsed = 0.0
    if ([double]::TryParse($text, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
        return $parsed
    }
    if ([double]::TryParse($text, [ref]$parsed)) { return $parsed }
    return 0.0
}

function Convert-ToInt64 {
    param([object]$Value)
    $text = [string]$Value
    if ([string]::IsNullOrWhiteSpace($text)) { return [int64]0 }
    $parsed = [int64]0
    if ([int64]::TryParse($text, [ref]$parsed)) { return $parsed }
    return [int64]0
}

function Get-RowValue {
    param(
        [object]$Row,
        [string]$Name,
        [object]$Default = ''
    )
    $property = $Row.PSObject.Properties[$Name]
    if ($null -eq $property -or $null -eq $property.Value) { return $Default }
    return $property.Value
}

function Get-FormulaImageAssessment {
    param([object]$Row)

    $score = 0
    $reasons = New-Object System.Collections.Generic.List[string]
    $edgeDensity = Convert-ToDouble (Get-RowValue -Row $Row -Name 'EdgeDensity')
    $colorDiversity = Convert-ToDouble (Get-RowValue -Row $Row -Name 'ColorDiversity')
    $grayRatio = Convert-ToDouble (Get-RowValue -Row $Row -Name 'GrayRatio')
    $transparentRatio = Convert-ToDouble (Get-RowValue -Row $Row -Name 'TransparentRatio')
    $uniqueColorBins = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'UniqueColorBins')
    $pixels = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'Pixels')
    $width = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'Width')
    $height = Convert-ToInt64 (Get-RowValue -Row $Row -Name 'Height')
    $candidateLevel = [string](Get-RowValue -Row $Row -Name 'CandidateLevel')
    $mediaRole = [string](Get-RowValue -Row $Row -Name 'MediaRole' -Default 'StandaloneImage')

    if ($mediaRole -ne 'StandaloneImage') {
        return [pscustomobject]@{
            FormulaImageScore = 0
            FormulaImageCandidate = $false
            FormulaCandidateLevel = 'Excluded'
            FormulaCandidateReason = 'Not a standalone image'
        }
    }

    if ($candidateLevel -eq 'LikelyDiagramOrText') {
        $score += 25
        $reasons.Add('diagram/text classifier') | Out-Null
    } elseif ($candidateLevel -eq 'TooSmall') {
        $score -= 10
        $reasons.Add('small image') | Out-Null
    }

    if ($edgeDensity -ge 0.18) {
        $score += 30
        $reasons.Add('high edge density') | Out-Null
    } elseif ($edgeDensity -ge 0.10) {
        $score += 18
        $reasons.Add('moderate edge density') | Out-Null
    } elseif ($edgeDensity -lt 0.03) {
        $score -= 10
        $reasons.Add('low edge density') | Out-Null
    }

    if ($colorDiversity -le 0.08) {
        $score += 15
        $reasons.Add('low color diversity') | Out-Null
    } elseif ($colorDiversity -ge 0.18) {
        $score -= 10
        $reasons.Add('photo-like color diversity') | Out-Null
    }

    if ($grayRatio -ge 0.65) {
        $score += 12
        $reasons.Add('mostly grayscale') | Out-Null
    }

    if ($uniqueColorBins -le 220 -and $uniqueColorBins -gt 0) {
        $score += 8
        $reasons.Add('limited color bins') | Out-Null
    }

    if ($transparentRatio -gt 0.02) {
        $score += 6
        $reasons.Add('transparent overlay asset') | Out-Null
    }

    if ($pixels -ge 5000 -and $pixels -le 2500000) {
        $score += 5
    }

    if ($width -gt 0 -and $height -gt 0) {
        $ratio = [Math]::Max($width, $height) / [double][Math]::Max(1, [Math]::Min($width, $height))
        if ($ratio -ge 2.5) {
            $score += 5
            $reasons.Add('wide or tall formula-like aspect') | Out-Null
        }
    }

    $boundedScore = [Math]::Max(0, [Math]::Min(100, $score))
    $isCandidate = $boundedScore -ge $MinScore
    $level = if ($boundedScore -ge 70) {
        'LikelyFormulaImage'
    } elseif ($isCandidate) {
        'MaybeFormulaImage'
    } else {
        'UnlikelyFormulaImage'
    }

    if ($reasons.Count -eq 0) { $reasons.Add('No formula-like visual signals') | Out-Null }
    return [pscustomobject]@{
        FormulaImageScore = $boundedScore
        FormulaImageCandidate = $isCandidate
        FormulaCandidateLevel = $level
        FormulaCandidateReason = ($reasons -join '; ')
    }
}

function Export-PptxMediaEntry {
    param(
        [string]$DeckPath,
        [string]$MediaPath,
        [string]$OutputPath
    )
    if (-not (Test-Path -LiteralPath $DeckPath)) { return $false }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $zip = $null
    $input = $null
    $output = $null
    try {
        $zip = [System.IO.Compression.ZipFile]::OpenRead($DeckPath)
        $entry = $zip.GetEntry($MediaPath)
        if ($null -eq $entry) { return $false }
        $outDir = Split-Path -Parent $OutputPath
        if (-not (Test-Path -LiteralPath $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
        $input = $entry.Open()
        $output = [System.IO.File]::Create($OutputPath)
        $input.CopyTo($output)
        return $true
    } finally {
        if ($null -ne $output) { $output.Dispose() }
        if ($null -ne $input) { $input.Dispose() }
        if ($null -ne $zip) { $zip.Dispose() }
    }
}

function New-FormulaContactSheet {
    param(
        [object[]]$Rows,
        [string]$OutputPath,
        [int]$MaxItems
    )

    Add-Type -AssemblyName System.Drawing
    $items = @($Rows |
        Where-Object { $_.FormulaImageCandidate -and -not [string]::IsNullOrWhiteSpace($_.FormulaExtractedPath) -and (Test-Path -LiteralPath $_.FormulaExtractedPath) } |
        Sort-Object FormulaImageScore -Descending |
        Select-Object -First $MaxItems)
    if ($items.Count -eq 0) { return $false }

    $tileWidth = 300
    $tileHeight = 230
    $imageHeight = 150
    $columns = 4
    if ($items.Count -lt 4) { $columns = [Math]::Max(1, $items.Count) }
    $rowsCount = [int][Math]::Ceiling($items.Count / [double]$columns)
    $sheetWidth = $columns * $tileWidth
    $sheetHeight = $rowsCount * $tileHeight

    $bitmap = $null
    $graphics = $null
    $font = $null
    $smallFont = $null
    $pen = $null
    try {
        $bitmap = New-Object System.Drawing.Bitmap($sheetWidth, $sheetHeight)
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.Clear([System.Drawing.Color]::FromArgb(248, 248, 248))
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $font = New-Object System.Drawing.Font('Microsoft YaHei UI', 8.5)
        $smallFont = New-Object System.Drawing.Font('Microsoft YaHei UI', 7.5)
        $pen = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(210, 210, 210), 1)

        for ($i = 0; $i -lt $items.Count; $i++) {
            $row = [int][Math]::Floor($i / $columns)
            $col = $i % $columns
            $x = $col * $tileWidth
            $y = $row * $tileHeight
            $graphics.FillRectangle([System.Drawing.Brushes]::White, $x + 6, $y + 6, $tileWidth - 12, $tileHeight - 12)
            $graphics.DrawRectangle($pen, $x + 6, $y + 6, $tileWidth - 12, $tileHeight - 12)

            $img = $null
            try {
                $img = [System.Drawing.Image]::FromFile($items[$i].FormulaExtractedPath)
                $maxW = $tileWidth - 24
                $maxH = $imageHeight
                $scale = [Math]::Min($maxW / [double]$img.Width, $maxH / [double]$img.Height)
                $drawW = [Math]::Max(1, [int][Math]::Round($img.Width * $scale))
                $drawH = [Math]::Max(1, [int][Math]::Round($img.Height * $scale))
                $drawX = $x + [int](($tileWidth - $drawW) / 2)
                $drawY = $y + 14 + [int](($imageHeight - $drawH) / 2)
                $graphics.DrawImage($img, $drawX, $drawY, $drawW, $drawH)
            } finally {
                if ($null -ne $img) { $img.Dispose() }
            }

            $labelY = $y + $imageHeight + 18
            $deck = [System.IO.Path]::GetFileNameWithoutExtension([string]$items[$i].Deck)
            if ($deck.Length -gt 18) { $deck = $deck.Substring(0, 18) + '...' }
            $line1 = "$($items[$i].FormulaCandidateLevel) score=$($items[$i].FormulaImageScore)"
            $line2 = "$deck / slides: $($items[$i].UsedOnSlides)"
            $line3 = [string]$items[$i].MediaPath
            $graphics.DrawString($line1, $font, [System.Drawing.Brushes]::Black, $x + 12, $labelY)
            $graphics.DrawString($line2, $smallFont, [System.Drawing.Brushes]::DimGray, $x + 12, $labelY + 20)
            $graphics.DrawString($line3, $smallFont, [System.Drawing.Brushes]::DimGray, $x + 12, $labelY + 38)
        }

        $bitmap.Save($OutputPath, [System.Drawing.Imaging.ImageFormat]::Png)
        return $true
    } finally {
        if ($null -ne $pen) { $pen.Dispose() }
        if ($null -ne $smallFont) { $smallFont.Dispose() }
        if ($null -ne $font) { $font.Dispose() }
        if ($null -ne $graphics) { $graphics.Dispose() }
        if ($null -ne $bitmap) { $bitmap.Dispose() }
    }
}

$ImageCandidateCsv = [System.IO.Path]::GetFullPath($ImageCandidateCsv)
$OutputDir = [System.IO.Path]::GetFullPath($OutputDir)
if (-not (Test-Path -LiteralPath $ImageCandidateCsv)) { throw "ImageCandidateCsv not found: $ImageCandidateCsv" }
if (-not (Test-Path -LiteralPath $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$extractDir = Join-Path $OutputDir 'formula-image-candidates'
if ($ExportCandidates -and -not (Test-Path -LiteralPath $extractDir)) {
    New-Item -ItemType Directory -Path $extractDir -Force | Out-Null
}

$sourceRows = @(Import-Csv -LiteralPath $ImageCandidateCsv -Encoding UTF8)
$rows = New-Object System.Collections.Generic.List[object]
foreach ($row in $sourceRows) {
    $assessment = Get-FormulaImageAssessment -Row $row
    $extractedPath = ''
    if ($ExportCandidates -and $assessment.FormulaImageCandidate) {
        $deckSafe = Convert-ToSafePathSegment -Name ([System.IO.Path]::GetFileNameWithoutExtension([string](Get-RowValue -Row $row -Name 'Deck')))
        $mediaPath = [string](Get-RowValue -Row $row -Name 'MediaPath')
        $mediaName = [System.IO.Path]::GetFileName($mediaPath)
        $mediaSafe = Convert-ToSafePathSegment -Name ([System.IO.Path]::GetFileNameWithoutExtension($mediaName))
        $ext = [System.IO.Path]::GetExtension($mediaName)
        if ([string]::IsNullOrWhiteSpace($ext)) { $ext = [string](Get-RowValue -Row $row -Name 'Extension') }
        $targetPath = Join-Path $extractDir ($deckSafe + '__' + $mediaSafe + $ext)
        if (Export-PptxMediaEntry -DeckPath ([string](Get-RowValue -Row $row -Name 'DeckPath')) -MediaPath $mediaPath -OutputPath $targetPath) {
            $extractedPath = $targetPath
        }
    }

    $rows.Add([pscustomobject]@{
        Deck = Get-RowValue -Row $row -Name 'Deck'
        DeckPath = Get-RowValue -Row $row -Name 'DeckPath'
        MediaPath = Get-RowValue -Row $row -Name 'MediaPath'
        Extension = Get-RowValue -Row $row -Name 'Extension'
        MediaRole = Get-RowValue -Row $row -Name 'MediaRole' -Default 'StandaloneImage'
        UsedOnSlides = Get-RowValue -Row $row -Name 'UsedOnSlides'
        OriginalBytes = Get-RowValue -Row $row -Name 'OriginalBytes'
        Width = Get-RowValue -Row $row -Name 'Width'
        Height = Get-RowValue -Row $row -Name 'Height'
        Pixels = Get-RowValue -Row $row -Name 'Pixels'
        ColorDiversity = Get-RowValue -Row $row -Name 'ColorDiversity'
        GrayRatio = Get-RowValue -Row $row -Name 'GrayRatio'
        TransparentRatio = Get-RowValue -Row $row -Name 'TransparentRatio'
        EdgeDensity = Get-RowValue -Row $row -Name 'EdgeDensity'
        SourceCandidateLevel = Get-RowValue -Row $row -Name 'CandidateLevel'
        FormulaImageScore = $assessment.FormulaImageScore
        FormulaImageCandidate = $assessment.FormulaImageCandidate
        FormulaCandidateLevel = $assessment.FormulaCandidateLevel
        FormulaCandidateReason = $assessment.FormulaCandidateReason
        FormulaExtractedPath = $extractedPath
        SuggestedAction = if ($assessment.FormulaImageCandidate) { 'ReviewImageFormulaOcr' } else { 'IgnoreForFormulaOcr' }
    }) | Out-Null
}

$csvPath = Join-Path $OutputDir 'formula-image-candidates.csv'
$jsonPath = Join-Path $OutputDir 'formula-image-candidates.json'
$manifestPath = Join-Path $OutputDir 'formula-image-candidates-manifest.json'
$contactSheetPath = Join-Path $OutputDir 'formula-image-candidates.contact-sheet.png'

$sorted = @($rows | Sort-Object @{ Expression = 'FormulaImageCandidate'; Descending = $true }, @{ Expression = 'FormulaImageScore'; Descending = $true }, Deck, MediaPath)
$sorted | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8
$sorted | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$contactSheetCreated = $false
if ($ContactSheet) {
    $contactSheetCreated = New-FormulaContactSheet -Rows $sorted -OutputPath $contactSheetPath -MaxItems $MaxContactSheetItems
}

$candidateRows = @($rows | Where-Object { $_.FormulaImageCandidate })
$manifest = [pscustomobject]@{
    generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    imageCandidateCsv = $ImageCandidateCsv
    outputDir = $OutputDir
    rowCount = $rows.Count
    formulaImageCandidateCount = $candidateRows.Count
    minScore = $MinScore
    csv = $csvPath
    json = $jsonPath
    extractedDir = if ($ExportCandidates) { $extractDir } else { '' }
    contactSheet = if ($contactSheetCreated) { $contactSheetPath } else { '' }
    note = 'Read-only formula image candidate scan. OCR and replacement require separate review gates.'
}
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Write-Host "Formula image candidate scan done: $OutputDir"
Write-Host "Candidates: $($candidateRows.Count) / Images: $($rows.Count)"
