<#
.SYNOPSIS
  Export editable formula candidates as MathML and OfficeMath/OMML XML fragments.

.DESCRIPTION
  Reads formula-review.csv and converts whitelist rows with
  SuggestedAction=ReviewWhitelistConversion into reviewable XML fragments.
  This tool does not modify PPTX files. It is the safe handoff between
  formula review and a future PPTX OfficeMath writer.

.PARAMETER FormulaReviewCsv
  formula-review.csv generated by Invoke-PhysicsPptWorkflow.ps1.

.PARAMETER OutputDir
  Directory where CSV, JSON, MathML, and OMML fragments are written.

.PARAMETER MaxItems
  Maximum whitelist rows to export in one run.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$FormulaReviewCsv,

    [Parameter(Mandatory = $true)]
    [string]$OutputDir,

    [ValidateRange(1, 1000)]
    [int]$MaxItems = 100
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:NsA14 = 'http://schemas.microsoft.com/office/drawing/2010/main'
$script:NsA = 'http://schemas.openxmlformats.org/drawingml/2006/main'
$script:NsM = 'http://schemas.openxmlformats.org/officeDocument/2006/math'
$script:NsMathMl = 'http://www.w3.org/1998/Math/MathML'
$script:FormulaWhitelist = @()

$configPath = Join-Path (Split-Path -Parent $PSScriptRoot) 'config\physics-ppt-style.config.json'
if (Test-Path -LiteralPath $configPath) {
    try {
        $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($null -ne $config.formulaWhitelist) {
            $script:FormulaWhitelist = @($config.formulaWhitelist)
        }
    } catch {
        Write-Warning "Formula config could not be loaded: $($_.Exception.Message)"
    }
}

function Convert-ToSafePathSegment {
    param([string]$Name)
    $safe = $Name
    foreach ($ch in [System.IO.Path]::GetInvalidFileNameChars()) {
        $safe = $safe.Replace([string]$ch, '_')
    }
    $safe = $safe -replace '\s+', '_'
    $safe = $safe -replace '[^\p{L}\p{Nd}_-]+', '_'
    $safe = $safe.Trim('_')
    if ([string]::IsNullOrWhiteSpace($safe)) { return 'formula' }
    return $safe
}

function Get-FormulaDetailValue {
    param([string]$Details, [string]$Key)
    if ([string]::IsNullOrWhiteSpace($Details)) { return '' }
    $pattern = '(?:^|;\s*)' + [regex]::Escape($Key) + '=(.*?)(?=;\s*\w+=|$)'
    $match = [regex]::Match($Details, $pattern)
    if (-not $match.Success) { return '' }
    return $match.Groups[1].Value.Trim()
}

function Get-NormalizedFormulaText {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return '' }
    return (($Text -replace '\s+', '') -replace '＝', '=').Trim()
}

function Get-FormulaRuleValue {
    param($Rule, [string]$Name, [string]$Default = '')
    if ($null -eq $Rule) { return $Default }
    $prop = $Rule.PSObject.Properties[$Name]
    if ($null -eq $prop -or $null -eq $prop.Value) { return $Default }
    return [string]$prop.Value
}

function Get-CurrentWhitelistRule {
    param([string]$FormulaText)
    $normalized = Get-NormalizedFormulaText -Text $FormulaText
    if ([string]::IsNullOrWhiteSpace($normalized)) { return $null }

    foreach ($rule in @($script:FormulaWhitelist)) {
        $pattern = Get-FormulaRuleValue -Rule $rule -Name 'sourcePattern'
        if ([string]::IsNullOrWhiteSpace($pattern)) { continue }
        try {
            if ($normalized -match $pattern) { return $rule }
        } catch {
            continue
        }
    }
    return $null
}

function New-Element {
    param(
        [System.Xml.XmlDocument]$Document,
        [string]$Prefix,
        [string]$Name,
        [string]$Namespace
    )
    return $Document.CreateElement($Prefix, $Name, $Namespace)
}

function Add-TextElement {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Prefix,
        [string]$Name,
        [string]$Namespace,
        [string]$Text
    )
    $el = New-Element -Document $Document -Prefix $Prefix -Name $Name -Namespace $Namespace
    $el.AppendChild($Document.CreateTextNode($Text)) | Out-Null
    $Parent.AppendChild($el) | Out-Null
    return $el
}

function New-RunProperties {
    param([System.Xml.XmlDocument]$Document)
    $rPr = New-Element -Document $Document -Prefix 'a' -Name 'rPr' -Namespace $script:NsA
    $rPr.SetAttribute('lang', 'en-US')
    $rPr.SetAttribute('altLang', 'zh-CN')
    $rPr.SetAttribute('sz', '3800')
    $rPr.SetAttribute('i', '1')

    $solidFill = New-Element -Document $Document -Prefix 'a' -Name 'solidFill' -Namespace $script:NsA
    $srgb = New-Element -Document $Document -Prefix 'a' -Name 'srgbClr' -Namespace $script:NsA
    $srgb.SetAttribute('val', '0066CC')
    $solidFill.AppendChild($srgb) | Out-Null
    $rPr.AppendChild($solidFill) | Out-Null

    $latin = New-Element -Document $Document -Prefix 'a' -Name 'latin' -Namespace $script:NsA
    $latin.SetAttribute('typeface', 'Cambria Math')
    $rPr.AppendChild($latin) | Out-Null
    return $rPr
}

function Add-OmmlRun {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Text
    )
    if ([string]::IsNullOrEmpty($Text)) { return }
    $run = New-Element -Document $Document -Prefix 'm' -Name 'r' -Namespace $script:NsM
    $run.AppendChild((New-RunProperties -Document $Document)) | Out-Null
    Add-TextElement -Document $Document -Parent $run -Prefix 'm' -Name 't' -Namespace $script:NsM -Text $Text | Out-Null
    $Parent.AppendChild($run) | Out-Null
}

function Add-OmmlToken {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Token
    )
    $trimmed = $Token.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { return }

    if ($trimmed -match '^([+\-−])(.+)$') {
        Add-OmmlRun -Document $Document -Parent $Parent -Text $Matches[1]
        Add-OmmlExpression -Document $Document -Parent $Parent -Expression $Matches[2]
        return
    }

    for ($i = 1; $i -lt ($trimmed.Length - 1); $i++) {
        $operator = $trimmed.Substring($i, 1)
        if ($operator -in @('+', '-', '−')) {
            Add-OmmlExpression -Document $Document -Parent $Parent -Expression $trimmed.Substring(0, $i)
            Add-OmmlRun -Document $Document -Parent $Parent -Text $operator
            Add-OmmlExpression -Document $Document -Parent $Parent -Expression $trimmed.Substring($i + 1)
            return
        }
    }

    if ($trimmed -match '^(.+?)_([物总有额动排液]|[0-9]+)(.*)$') {
        $sub = New-Element -Document $Document -Prefix 'm' -Name 'sSub' -Namespace $script:NsM
        $base = New-Element -Document $Document -Prefix 'm' -Name 'e' -Namespace $script:NsM
        $subscript = New-Element -Document $Document -Prefix 'm' -Name 'sub' -Namespace $script:NsM
        Add-OmmlExpression -Document $Document -Parent $base -Expression $Matches[1]
        Add-OmmlExpression -Document $Document -Parent $subscript -Expression $Matches[2]
        $sub.AppendChild($base) | Out-Null
        $sub.AppendChild($subscript) | Out-Null
        $Parent.AppendChild($sub) | Out-Null
        if (-not [string]::IsNullOrWhiteSpace($Matches[3])) {
            Add-OmmlExpression -Document $Document -Parent $Parent -Expression $Matches[3]
        }
        return
    }

    Add-OmmlRun -Document $Document -Parent $Parent -Text $trimmed
}

function Add-OmmlFraction {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Numerator,
        [string]$Denominator
    )
    $frac = New-Element -Document $Document -Prefix 'm' -Name 'f' -Namespace $script:NsM
    $fracPr = New-Element -Document $Document -Prefix 'm' -Name 'fPr' -Namespace $script:NsM
    $ctrlPr = New-Element -Document $Document -Prefix 'm' -Name 'ctrlPr' -Namespace $script:NsM
    $ctrlPr.AppendChild((New-RunProperties -Document $Document)) | Out-Null
    $fracPr.AppendChild($ctrlPr) | Out-Null
    $frac.AppendChild($fracPr) | Out-Null

    $num = New-Element -Document $Document -Prefix 'm' -Name 'num' -Namespace $script:NsM
    Add-OmmlExpression -Document $Document -Parent $num -Expression $Numerator
    $den = New-Element -Document $Document -Prefix 'm' -Name 'den' -Namespace $script:NsM
    Add-OmmlExpression -Document $Document -Parent $den -Expression $Denominator
    $frac.AppendChild($num) | Out-Null
    $frac.AppendChild($den) | Out-Null
    $Parent.AppendChild($frac) | Out-Null
}

function Add-OmmlExpression {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Expression
    )
    $expr = ($Expression -replace '\s+', ' ').Trim()
    if ([string]::IsNullOrWhiteSpace($expr)) { return }

    $slashParts = @($expr -split '/', 2)
    if ($slashParts.Count -eq 2 -and -not [string]::IsNullOrWhiteSpace($slashParts[0]) -and -not [string]::IsNullOrWhiteSpace($slashParts[1])) {
        Add-OmmlFraction -Document $Document -Parent $Parent -Numerator $slashParts[0] -Denominator $slashParts[1]
        return
    }

    $parts = @($expr -split ' ' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    for ($i = 0; $i -lt $parts.Count; $i++) {
        if ($i -gt 0) { Add-OmmlRun -Document $Document -Parent $Parent -Text ' ' }
        Add-OmmlToken -Document $Document -Parent $Parent -Token $parts[$i]
    }
}

function New-OmmlFragment {
    param([string]$UnicodeMath)
    $doc = New-Object System.Xml.XmlDocument
    $root = New-Element -Document $doc -Prefix 'a14' -Name 'm' -Namespace $script:NsA14
    $root.SetAttribute('xmlns:a14', $script:NsA14)
    $root.SetAttribute('xmlns:a', $script:NsA)
    $root.SetAttribute('xmlns:m', $script:NsM)
    $doc.AppendChild($root) | Out-Null

    $oMath = New-Element -Document $doc -Prefix 'm' -Name 'oMath' -Namespace $script:NsM
    $root.AppendChild($oMath) | Out-Null

    $parts = @($UnicodeMath -split '=', 2)
    if ($parts.Count -eq 2) {
        Add-OmmlExpression -Document $doc -Parent $oMath -Expression $parts[0]
        Add-OmmlRun -Document $doc -Parent $oMath -Text '='
        Add-OmmlExpression -Document $doc -Parent $oMath -Expression $parts[1]
    } else {
        Add-OmmlExpression -Document $doc -Parent $oMath -Expression $UnicodeMath
    }

    return $doc
}

function Add-MathMlOperator {
    param([System.Xml.XmlDocument]$Document, [System.Xml.XmlElement]$Parent, [string]$Text)
    Add-TextElement -Document $Document -Parent $Parent -Prefix '' -Name 'mo' -Namespace $script:NsMathMl -Text $Text | Out-Null
}

function Add-MathMlToken {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Token
    )
    $trimmed = $Token.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed)) { return }

    if ($trimmed -match '^([+\-−])(.+)$') {
        Add-MathMlOperator -Document $Document -Parent $Parent -Text $Matches[1]
        Add-MathMlExpression -Document $Document -Parent $Parent -Expression $Matches[2]
        return
    }

    for ($i = 1; $i -lt ($trimmed.Length - 1); $i++) {
        $operator = $trimmed.Substring($i, 1)
        if ($operator -in @('+', '-', '−')) {
            Add-MathMlExpression -Document $Document -Parent $Parent -Expression $trimmed.Substring(0, $i)
            Add-MathMlOperator -Document $Document -Parent $Parent -Text $operator
            Add-MathMlExpression -Document $Document -Parent $Parent -Expression $trimmed.Substring($i + 1)
            return
        }
    }

    if ($trimmed -match '^(.+?)_([物总有额动排液]|[0-9]+)(.*)$') {
        $msub = New-Element -Document $Document -Prefix '' -Name 'msub' -Namespace $script:NsMathMl
        Add-MathMlExpression -Document $Document -Parent $msub -Expression $Matches[1]
        Add-MathMlExpression -Document $Document -Parent $msub -Expression $Matches[2]
        $Parent.AppendChild($msub) | Out-Null
        if (-not [string]::IsNullOrWhiteSpace($Matches[3])) {
            Add-MathMlExpression -Document $Document -Parent $Parent -Expression $Matches[3]
        }
        return
    }

    $tag = if ($trimmed -match '^[0-9]+(?:\.[0-9]+)?$') {
        'mn'
    } elseif ($trimmed -match '^[A-Za-zΑ-ωρτηηΩμ]+$' -and $trimmed.Length -le 2) {
        'mi'
    } else {
        'mtext'
    }
    Add-TextElement -Document $Document -Parent $Parent -Prefix '' -Name $tag -Namespace $script:NsMathMl -Text $trimmed | Out-Null
}

function Add-MathMlExpression {
    param(
        [System.Xml.XmlDocument]$Document,
        [System.Xml.XmlElement]$Parent,
        [string]$Expression
    )
    $expr = ($Expression -replace '\s+', ' ').Trim()
    if ([string]::IsNullOrWhiteSpace($expr)) { return }

    $slashParts = @($expr -split '/', 2)
    if ($slashParts.Count -eq 2 -and -not [string]::IsNullOrWhiteSpace($slashParts[0]) -and -not [string]::IsNullOrWhiteSpace($slashParts[1])) {
        $mfrac = New-Element -Document $Document -Prefix '' -Name 'mfrac' -Namespace $script:NsMathMl
        $num = New-Element -Document $Document -Prefix '' -Name 'mrow' -Namespace $script:NsMathMl
        $den = New-Element -Document $Document -Prefix '' -Name 'mrow' -Namespace $script:NsMathMl
        Add-MathMlExpression -Document $Document -Parent $num -Expression $slashParts[0]
        Add-MathMlExpression -Document $Document -Parent $den -Expression $slashParts[1]
        $mfrac.AppendChild($num) | Out-Null
        $mfrac.AppendChild($den) | Out-Null
        $Parent.AppendChild($mfrac) | Out-Null
        return
    }

    $parts = @($expr -split ' ' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    for ($i = 0; $i -lt $parts.Count; $i++) {
        if ($i -gt 0) { Add-MathMlOperator -Document $Document -Parent $Parent -Text ([string][char]0x2062) }
        Add-MathMlToken -Document $Document -Parent $Parent -Token $parts[$i]
    }
}

function New-MathMlFragment {
    param([string]$UnicodeMath)
    $doc = New-Object System.Xml.XmlDocument
    $math = New-Element -Document $doc -Prefix '' -Name 'math' -Namespace $script:NsMathMl
    $math.SetAttribute('xmlns', $script:NsMathMl)
    $math.SetAttribute('display', 'block')
    $doc.AppendChild($math) | Out-Null
    $mrow = New-Element -Document $doc -Prefix '' -Name 'mrow' -Namespace $script:NsMathMl
    $math.AppendChild($mrow) | Out-Null

    $parts = @($UnicodeMath -split '=', 2)
    if ($parts.Count -eq 2) {
        Add-MathMlExpression -Document $doc -Parent $mrow -Expression $parts[0]
        Add-MathMlOperator -Document $doc -Parent $mrow -Text '='
        Add-MathMlExpression -Document $doc -Parent $mrow -Expression $parts[1]
    } else {
        Add-MathMlExpression -Document $doc -Parent $mrow -Expression $UnicodeMath
    }

    return $doc
}

function Convert-XmlDocumentToString {
    param([System.Xml.XmlDocument]$Document)
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Indent = $true
    $settings.OmitXmlDeclaration = $true
    $builder = New-Object System.Text.StringBuilder
    $writer = [System.Xml.XmlWriter]::Create($builder, $settings)
    try {
        $Document.Save($writer)
    } finally {
        if ($null -ne $writer) { $writer.Dispose() }
    }
    return $builder.ToString()
}

function Write-Utf8BomText {
    param([string]$Path, [string]$Text)
    $utf8Bom = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Path, $Text, $utf8Bom)
}

$FormulaReviewCsv = [System.IO.Path]::GetFullPath($FormulaReviewCsv)
$OutputDir = [System.IO.Path]::GetFullPath($OutputDir)
if (-not (Test-Path -LiteralPath $FormulaReviewCsv)) { throw "FormulaReviewCsv not found: $FormulaReviewCsv" }
if (-not (Test-Path -LiteralPath $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }

$fragmentDir = Join-Path $OutputDir 'fragments'
if (-not (Test-Path -LiteralPath $fragmentDir)) { New-Item -ItemType Directory -Path $fragmentDir -Force | Out-Null }

$reviewRows = @(
    Import-Csv -LiteralPath $FormulaReviewCsv -Encoding UTF8 |
        Where-Object { $_.SuggestedAction -eq 'ReviewWhitelistConversion' -and -not [string]::IsNullOrWhiteSpace($_.WhitelistCandidate) } |
        Select-Object -First $MaxItems
)

$results = New-Object System.Collections.Generic.List[object]
for ($i = 0; $i -lt $reviewRows.Count; $i++) {
    $row = $reviewRows[$i]
    $name = Get-FormulaDetailValue -Details ([string]$row.WhitelistCandidate) -Key 'name'
    $targetUnicodeMath = Get-FormulaDetailValue -Details ([string]$row.WhitelistCandidate) -Key 'targetUnicodeMath'
    $targetTex = Get-FormulaDetailValue -Details ([string]$row.WhitelistCandidate) -Key 'targetTex'
    $currentRule = Get-CurrentWhitelistRule -FormulaText ([string]$row.FormulaText)
    if ($null -ne $currentRule) {
        $name = Get-FormulaRuleValue -Rule $currentRule -Name 'name' -Default $name
        $targetUnicodeMath = Get-FormulaRuleValue -Rule $currentRule -Name 'targetUnicodeMath' -Default $targetUnicodeMath
        $targetTex = Get-FormulaRuleValue -Rule $currentRule -Name 'targetTex' -Default $targetTex
    }
    $fileStem = if ($null -ne $row.PSObject.Properties['FileRelativePath'] -and -not [string]::IsNullOrWhiteSpace([string]$row.FileRelativePath)) {
        Convert-ToSafePathSegment -Name ([string]$row.FileRelativePath -replace '[\\/]', '__')
    } elseif ($null -ne $row.PSObject.Properties['FilePath'] -and -not [string]::IsNullOrWhiteSpace([string]$row.FilePath)) {
        Convert-ToSafePathSegment -Name ([System.IO.Path]::GetFileNameWithoutExtension([string]$row.FilePath))
    } else {
        Convert-ToSafePathSegment -Name ([string]$row.File)
    }
    $baseName = '{0:000}_{1}_slide-{2:000}_{3}_{4}' -f ($i + 1), $fileStem, ([int]$row.Slide), (Convert-ToSafePathSegment -Name ([string]$row.Shape)), (Convert-ToSafePathSegment -Name $name)
    $ommlPath = Join-Path $fragmentDir ($baseName + '.omml.xml')
    $mathMlPath = Join-Path $fragmentDir ($baseName + '.mathml.xml')

    $status = 'Generated'
    $message = ''
    try {
        if ([string]::IsNullOrWhiteSpace($targetUnicodeMath)) {
            throw 'WhitelistCandidate does not contain targetUnicodeMath.'
        }
        $ommlDoc = New-OmmlFragment -UnicodeMath $targetUnicodeMath
        $mathMlDoc = New-MathMlFragment -UnicodeMath $targetUnicodeMath
        Write-Utf8BomText -Path $ommlPath -Text (Convert-XmlDocumentToString -Document $ommlDoc)
        Write-Utf8BomText -Path $mathMlPath -Text (Convert-XmlDocumentToString -Document $mathMlDoc)
    } catch {
        $status = 'Failed'
        $message = $_.Exception.Message
        $ommlPath = ''
        $mathMlPath = ''
    }

    $results.Add([pscustomobject]@{
        File = $row.File
        FilePath = if ($null -ne $row.PSObject.Properties['FilePath']) { [string]$row.FilePath } else { [string]$row.File }
        Slide = $row.Slide
        Shape = $row.Shape
        FormulaText = $row.FormulaText
        Name = $name
        TargetUnicodeMath = $targetUnicodeMath
        TargetTex = $targetTex
        TargetSource = if ($null -ne $currentRule) { 'CurrentConfig' } else { 'FormulaReviewCsv' }
        OmmlFragment = $ommlPath
        MathMlFragment = $mathMlPath
        Status = $status
        Message = $message
    }) | Out-Null
}

$csvPath = Join-Path $OutputDir 'formula-omml-candidates.csv'
$jsonPath = Join-Path $OutputDir 'formula-omml-candidates.json'
$manifestPath = Join-Path $OutputDir 'formula-omml-candidates-manifest.json'

$results | Export-Csv -LiteralPath $csvPath -NoTypeInformation -Encoding UTF8
$results | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding UTF8

$manifest = [pscustomobject]@{
    generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    formulaReviewCsv = $FormulaReviewCsv
    outputDir = $OutputDir
    fragmentDir = $fragmentDir
    candidateCount = $reviewRows.Count
    generatedCount = @($results | Where-Object { $_.Status -eq 'Generated' }).Count
    failedCount = @($results | Where-Object { $_.Status -ne 'Generated' }).Count
    csv = $csvPath
    json = $jsonPath
    note = 'Fragments are review artifacts. They are not inserted into PPTX by this tool.'
}
$manifest | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Write-Host "OMML candidate export done: $OutputDir"
Write-Host "Generated: $($manifest.generatedCount) / Candidates: $($manifest.candidateCount)"
